### PR TITLE
Make PlatformConfiguration properties trimmable (fixes tvOS compilation)

### LINKED ISSUE #2715: [BUG] Publishing tvOS application with SkiaSharp fails
### Description

When I am trying to publish a tvOS app with SkiaSharp referenced, compilation fails.
It works well when I am running in debug with simulator though. 

### Code

Pretty much any usage of SkiaSharp. For example:

```cs
using SkiaSharp;
using tv_test;

var info = new SKImageInfo(512, 512);
var surface = SKSurface.Create(info);
var canvas = surface.Canvas;
canvas.Clear(SKColors.White);

UIApplication.Main (args, null, typeof (AppDelegate));

```

To run:
```
dotnet publish -c Release -r tvos-arm64
```

[Archive.zip](https://github.com/mono/SkiaSharp/files/13930830/Archive.zip)

### Expected Behavior

Application can be compiled.

### Actual Behavior

Compilation fails

### Version of SkiaSharp

2.88.3 (Current)

### Last Known Good Version of SkiaSharp

Other (Please indicate in the description)

### IDE / Editor

Other (Please indicate in the description)

### Platform / Operating System

tvOS

### Platform / Operating System Version

tvOS: 13.0+

### Devices

Apple TV

### Relevant Screenshots

_No response_

### Relevant Log Output

```shell
tvtest -> /Users/maxkatz6/repos/trash-bin/tvtest/bin/Release/net8.0-tvos/tvos-arm64/tvtest.dll
  Optimizing assemblies for size may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
  Optimizing assemblies for size. This process might take a while.
  Tool xcrun execution finished (exit code = 1).
          
  Undefined symbols for architecture arm64:
    "_DeleteCriticalSection", referenced from:
        wrapper_managed_to_native_SkiaSharp_Internals_PlatformLock_NonAlertableWin32Lock_DeleteCriticalSection_intptr in SkiaSharp.dll.o
       (maybe you meant: _p_112_plt_SkiaSharp_SkiaSharp_Internals_PlatformLock_NonAlertableWin32Lock_DeleteCriticalSection_intptr_llvm)
    "_EnterCriticalSection", referenced from:
        wrapper_managed_to_native_SkiaSharp_Internals_PlatformLock_NonAlertableWin32Lock_EnterCriticalSection_intptr in SkiaSharp.dll.o
       (maybe you meant: _p_114_plt_SkiaSharp_SkiaSharp_Internals_PlatformLock_NonAlertableWin32Lock_EnterCriticalSection_intptr_llvm)
    "_InitializeCriticalSectionEx", referenced from:
        wrapper_managed_to_native_SkiaSharp_Internals_PlatformLock_NonAlertableWin32Lock_InitializeCriticalSectionEx_intptr_uint_uint in SkiaSharp.dll.o
       (maybe you meant: _p_111_plt_SkiaSharp_SkiaSharp_Internals_PlatformLock_NonAlertableWin32Lock_InitializeCriticalSectionEx_intptr_uint_uint_llvm)
    "_LeaveCriticalSection", referenced from:
        wrapper_managed_to_native_SkiaSharp_Internals_PlatformLock_NonAlertableWin32Lock_LeaveCriticalSection_intptr in SkiaSharp.dll.o
       (maybe you meant: _p_115_plt_SkiaSharp_SkiaSharp_Internals_PlatformLock_NonAlertableWin32Lock_LeaveCriticalSection_intptr_llvm)
    "_gnu_get_libc_version", referenced from:
        wrapper_managed_to_native_SkiaSharp_Internals_PlatformConfiguration_gnu_get_libc_version in SkiaSharp.dll.o
       (maybe you meant: _p_145_plt_SkiaSharp_SkiaSharp_Internals_PlatformConfiguration_gnu_get_libc_version_llvm)
  ld: symbol(s) not found for architecture arm64
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  
/usr/local/share/dotnet/packs/Microsoft.tvOS.Sdk/17.0.8490/targets/Xamarin.Shared.Sdk.targets(1556,3): error : clang++ exited with code 1: [/Users/maxkatz6/repos/trash-bin/tvtest/tvtest.csproj]
/usr/local/share/dotnet/packs/Microsoft.tvOS.Sdk/17.0.8490/targets/Xamarin.Shared.Sdk.targets(1556,3): error : Undefined symbols for architecture arm64: [/Users/maxkatz6/repos/trash-bin/tvtest/tvtest.csproj]
/usr/local/share/dotnet/packs/Microsoft.tvOS.Sdk/17.0.8490/targets/Xamarin.Shared.Sdk.targets(1556,3): error :   "_DeleteCriticalSection", referenced from: [/Users/maxkatz6/repos/trash-bin/tvtest/tvtest.csproj]
/usr/local/share/dotnet/packs/Microsoft.tvOS.Sdk/17.0.8490/targets/Xamarin.Shared.Sdk.targets(1556,3): error :       wrapper_managed_to_native_SkiaSharp_Internals_PlatformLock_NonAlertableWin32Lock_DeleteCriticalSection_intptr in SkiaSharp.dll.o [/Users/maxkatz6/repos/trash-bin/tvtest/tvtest.csproj]
/usr/local/share/dotnet/packs/Microsoft.tvOS.Sdk/17.0.8490/targets/Xamarin.Shared.Sdk.targets(1556,3): error :      (maybe you meant: _p_112_plt_SkiaSharp_SkiaSharp_Internals_PlatformLock_NonAlertableWin32Lock_DeleteCriticalSection_intptr_llvm) [/Users/maxkatz6/repos/trash-bin/tvtest/tvtest.csproj]
/usr/local/share/dotnet/packs/Microsoft.tvOS.Sdk/17.0.8490/targets/Xamarin.Shared.Sdk.targets(1556,3): error :   "_EnterCriticalSection", referenced from: [/Users/maxkatz6/repos/trash-bin/tvtest/tvtest.csproj]
/usr/local/share/dotnet/packs/Microsoft.tvOS.Sdk/17.0.8490/targets/Xamarin.Shared.Sdk.targets(1556,3): error :       wrapper_managed_to_native_SkiaSharp_Internals_PlatformLock_NonAlertableWin32Lock_EnterCriticalSection_intptr in SkiaSharp.dll.o [/Users/maxkatz6/repos/trash-bin/tvtest/tvtest.csproj]
/usr/local/share/dotnet/packs/Microsoft.tvOS.Sdk/17.0.8490/targets/Xamarin.Shared.Sdk.targets(1556,3): error :      (maybe you meant: _p_114_plt_SkiaSharp_SkiaSharp_Internals_PlatformLock_NonAlertableWin32Lock_EnterCriticalSection_intptr_llvm) [/Users/maxkatz6/repos/trash-bin/tvtest/tvtest.csproj]
/usr/local/share/dotnet/packs/Microsoft.tvOS.Sdk/17.0.8490/targets/Xamarin.Shared.Sdk.targets(1556,3): error :   "_InitializeCriticalSectionEx", referenced from: [/Users/maxkatz6/repos/trash-bin/tvtest/tvtest.csproj]
/usr/local/share/dotnet/packs/Microsoft.tvOS.Sdk/17.0.8490/targets/Xamarin.Shared.Sdk.targets(1556,3): error :       wrapper_managed_to_native_SkiaSharp_Internals_PlatformLock_NonAlertableWin32Lock_InitializeCriticalSectionEx_intptr_uint_uint in SkiaSharp.dll.o [/Users/maxkatz6/repos/trash-bin/tvtest/tvtest.csproj]
/usr/local/share/dotnet/packs/Microsoft.tvOS.Sdk/17.0.8490/targets/Xamarin.Shared.Sdk.targets(1556,3): error :      (maybe you meant: _p_111_plt_SkiaSharp_SkiaSharp_Internals_PlatformLock_NonAlertableWin32Lock_InitializeCriticalSectionEx_intptr_uint_uint_llvm) [/Users/maxkatz6/repos/trash-bin/tvtest/tvtest.csproj]
/usr/local/share/dotnet/packs/Microsoft.tvOS.Sdk/17.0.8490/targets/Xamarin.Shared.Sdk.targets(1556,3): error :   "_L [/Users/maxkatz6/repos/trash-bin/tvtest/tvtest.csproj]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by maxkatz6**
**Description of Change**

Previously SkiaSharp used old APIs to conditionally execute platform specific APIs. Specifically, RuntimeInformation.IsOSPlatform is known to be non-trimmable.

It caused some Windows PInvokes to be included in the non-windows binaries. For most platform it didn't really cause any problems, but apparently tvOS linker is more sensitive (see #2715)

This PR changes PlatformConfiguration class:
1.  Use newer trimmer friendly `OperatingSystem.IsWindows()` method instead of non-trimmable `RuntimeInformation.IsOSPlatform (OSPlatform.Windows)`.
2. Remove static ctor, and instead move these checks to the property getters. 

On .NET6+ targets with trimmer enabled these calls will be eliminated and values will be inlined.

Non trimmed SkiaSharp:
Screenshot 2024-01-14 at 10 25 25 PM

Trimmed SkiaSharp with "-r tvos-arm64" (hint for the compiler to replace OperatingSystem.IsWindows with "false").
As we can see, windows specific class is completely removed as unused.
Screenshot 2024-01-14 at 10 25 35 PM

**Bugs Fixed**

- Fixes #2715

**API Changes**

None.

**Behavioral Changes**

None.

**Required skia PR**

None.

**PR Checklist**

- [ ] Has tests (if omitted, state reason in description)
- [x] Rebased on top of main at time of PR
- [ ] Merged related skia PRs
- [x] Changes adhere to coding standard
- [ ] Updated documentation

This PR should also be backportable with no conflicts.

### CODE REVIEW

**Comment by maxkatz6** [comment]
Alternatively, we can add more preprocessor conditional checks for each target, eliminating code blocks during per specific target framework. In this way SkiaSharp for "net7.0-tvos" would never include windows code to begin with.
Though, it's probably unnecessary. Also, it would complexity.

**Comment by maxkatz6** [comment]
@mattleibow hi! How does this PR look? CI build failing seems to be unrelated.

**Review by mattleibow — DISMISSED** [review]

**Comment by mattleibow** [comment]
Retrying thre build. Sometimes the tests explode for no reason.

**Comment by mattleibow** [comment]
The macos tests are still crashing... I have retried 5 times and a fail already retries by default...

**Comment by maxkatz6** [comment]
@mattleibow that's weird, as with .NET 6+, RuntimeInformation API should simply redirect to OperatingSystem API, making them equivalent (except of trimming capabilities): https://github.com/dotnet/runtime/blob/v6.0.26/src/libraries/System.Runtime.InteropServices.RuntimeInformation/src/System/Runtime/InteropServices/RuntimeInformation/RuntimeInformation.cs#L52

CI worker only when I tried to revert my changed... Trying to see if it works with `OperatingSystem.IsWindows ()` only.

**Comment by mattleibow** [comment]
I see some other PRs are crashing on macOS... I wonder if some of my GC tests are crashing on a newer .net service release. But this is green now, so I am thinking this is intermittant... It can't be the check is crashing the test runner...

**Comment by maxkatz6** [comment]
@mattleibow okay. Let me know if any changes are required from my side. I can rebase this PR back to the state where OperatingSystem was used on every platform, not only Windows.

**Comment by mattleibow** [comment]
Maybe do that, let's make this code right and I will continue to investigate why CI is crashing. It looks also to just be the public bot.

**Comment by maxkatz6** [comment]
@mattleibow done

**Review by mattleibow — APPROVED** [review]

**Pull request merged**
