### PR TITLE
Multitarget Views.Desktop.Common

### PR DESCRIPTION
**Pull request by bender2k14**
**Description of Change**

Recreating PR #1066, which was closed when I deleted by branch.

Changes `SkiaSharp.Views.Desktop.Common` to multitarget
- .NET Standard 2.0,
- .NET Framework 4.5, and
- .NET Core 3.0.

Also removes `SkiaSharp.Views.Desktop.Common.NetStandard` _and all references to it_ (which wasn't the case in PR #1066).

I don't know if any part of the automated builds/devops needs to change as well.  Someone should check that.

**Bugs Fixed**

Related to issue #1029.  This PR gets us closer to dual targeting .NET Framework and .NET Core for `SkiaSharp.Views.WPF`.

**API Changes**

None

**Behavioral Changes**

None (intended)

**PR Checklist**

- [ ] Has tests (if omitted, state reason in description)
- [ ] Rebased on top of master at time of PR
 - NA
- [x] Changes adhere to coding standard
- [ ] Updated documentation

### CODE REVIEW

**Comment by bender2k14** [comment]
Build still fails :(

Quoting https://github.com/mono/SkiaSharp/pull/1066#issuecomment-567354337
> Still failing for some reason. I'm AFK right now, I'll have a look as soon as I get back. Thanks for the
PR. Not sure how I missed this one.
>
> You might also want to have a look at the nuspec file and add the new platform.

There are no more references to `SkiaSharp.Views.Desktop.Common.NetStandard` (because I searched within all files in the repo and either removed the reference or changed it to `SkiaSharp.Views.Desktop.Common`).  None of those references were in a nuspec file, so I didn't make any changes to those.

And you are welcome for the PR :)  Feel free to delegate any work to me to get this to build.

**Comment by bender2k14** [comment]
I created PR #1068 to see if the first commit in the branch for this PR passes the automated build, which might help us figure out how to get both commits in the branch for this PR to pass the automated build.

**Comment by mattleibow** [comment]
@bender2k14 The build is actually passing.

The reason for the red is that one of the samples is failing because a public PR does not have access to the signing keys required for iOS. I used to have a public CI but we don't seem to have a big enough Azure to use that - or something - so I have to just use the private builds for now. Trying to get more parallel builds in public so we get better status. Sorry about that.

You don't need to do https://github.com/mono/SkiaSharp/pull/1068

**Comment by bender2k14** [comment]
> The build is actually passing.

Oh, great :)

> ...Trying to get more parallel builds in public so we get better status. Sorry about that.

That's ok.

Is there work left to do for this PR then?

**Comment by mattleibow** [comment]
Nothing :)

**Pull request merged**
