### PR TITLE
Disable log compression in pipeline.groovy

### PR DESCRIPTION
**Pull request by akoeplinger**
It's currently incompatible with the changes Jenkins is making as part of JEP-210: issues.jenkins-ci.org/browse/JENKINS-54680

### CODE REVIEW

**Comment by mikekinsman** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[scripts/pipeline.groovy](https://github.com/mono/SkiaSharp/blob/akoeplinger-patch-1/scripts/pipeline.groovy) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C11%5C26%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201811261734489431-708%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Byci6C8bPoSkFNQawlm9SJqvx21jwIPS0m7D%2F8dVNbE%3D&st=2018-11-26T17%3A32%3A05Z&se=2018-12-27T17%3A37%3A05Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mattleibow** [comment]
Thanks for the PR.

**Comment by akoeplinger** [comment]
@mattleibow sigh, turns out you actually need to make an empty `properties ( [ ] )` instead otherwise it'll keep the previous value: https://github.com/mono/SkiaSharp/pull/709

**Comment by mattleibow** [comment]
Thanks. I merged it.

**Comment by akoeplinger** [comment]
Does it automatically end up in the `development` branch or do I need another PR?

**Comment by mattleibow** [comment]
Automatic! Almost... I use the development branch for larger work items so I can have a "stable" master and an "almost stable" master :)

**Pull request merged**
