### PR TITLE
Testing PR Builder

### PR DESCRIPTION
**Pull request by mattleibow**

### CODE REVIEW

**Comment by mikekinsman** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[scripts/pipeline.groovy](https://github.com/mono/SkiaSharp/blob/dev/testing/scripts/pipeline.groovy) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C14%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201808141602421345-616%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=xJhQkwbo2w1qGQlqNeY6rCklESoSLUFFlHjlK8iam1I%3D&st=2018-08-14T15%3A59%3A48Z&se=2018-09-14T16%3A04%3A48Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[scripts/pipeline.groovy](https://github.com/mono/SkiaSharp/blob/dev/testing/scripts/pipeline.groovy) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C14%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201808141829333594-616%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=NRq4kk90zmYauzk7n0hq%2BM071TugP2z1ce9j%2BbX1H1U%3D&st=2018-08-14T18%3A26%3A41Z&se=2018-09-14T18%3A31%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[build.cake](https://github.com/mono/SkiaSharp/blob/dev/testing/build.cake) | :white_check_mark:Succeeded | |
[docs/xml/SkiaSharp.Views.Desktop/SKControl.xml](https://github.com/mono/SkiaSharp/blob/dev/testing/docs/xml/SkiaSharp.Views.Desktop/SKControl.xml) | :white_check_mark:Succeeded | |
[docs/xml/SkiaSharp.Views.Desktop/SKGLControl.xml](https://github.com/mono/SkiaSharp/blob/dev/testing/docs/xml/SkiaSharp.Views.Desktop/SKGLControl.xml) | :white_check_mark:Succeeded | |
[docs/xml/SkiaSharp.Views.Forms/SKCanvasView.xml](https://github.com/mono/SkiaSharp/blob/dev/testing/docs/xml/SkiaSharp.Views.Forms/SKCanvasView.xml) | :white_check_mark:Succeeded | |
[docs/xml/SkiaSharp.Views.Forms/SKGLView.xml](https://github.com/mono/SkiaSharp/blob/dev/testing/docs/xml/SkiaSharp.Views.Forms/SKGLView.xml) | :white_check_mark:Succeeded | |
[docs/xml/SkiaSharp/SKAutoCanvasRestore.xml](https://github.com/mono/SkiaSharp/blob/dev/testing/docs/xml/SkiaSharp/SKAutoCanvasRestore.xml) | :white_check_mark:Succeeded | |
[docs/xml/SkiaSharp/SKAutoLockPixels.xml](https://github.com/mono/SkiaSharp/blob/dev/testing/docs/xml/SkiaSharp/SKAutoLockPixels.xml) | :white_check_mark:Succeeded | |
[docs/xml/SkiaSharp/SKAutoMaskFreeImage.xml](https://github.com/mono/SkiaSharp/blob/dev/testing/docs/xml/SkiaSharp/SKAutoMaskFreeImage.xml) | :white_check_mark:Succeeded | |
[docs/xml/SkiaSharp/SKManagedStream.xml](https://github.com/mono/SkiaSharp/blob/dev/testing/docs/xml/SkiaSharp/SKManagedStream.xml) | :white_check_mark:Succeeded | |
[scripts/pipeline.groovy](https://github.com/mono/SkiaSharp/blob/dev/testing/scripts/pipeline.groovy) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C15%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201808150029208867-616%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=VWvXjpFrs5Txc1OeglU3ahDg8bqPkdpQ82%2BnIgCdfwY%3D&st=2018-08-15T00%3A26%3A51Z&se=2018-09-15T00%3A31%3A51Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[build.cake](https://github.com/mono/SkiaSharp/blob/dev/testing/build.cake) | :white_check_mark:Succeeded | |
[docs/xml/SkiaSharp.Views.Desktop/SKControl.xml](https://github.com/mono/SkiaSharp/blob/dev/testing/docs/xml/SkiaSharp.Views.Desktop/SKControl.xml) | :white_check_mark:Succeeded | |
[docs/xml/SkiaSharp.Views.Desktop/SKGLControl.xml](https://github.com/mono/SkiaSharp/blob/dev/testing/docs/xml/SkiaSharp.Views.Desktop/SKGLControl.xml) | :white_check_mark:Succeeded | |
[docs/xml/SkiaSharp.Views.Forms/SKCanvasView.xml](https://github.com/mono/SkiaSharp/blob/dev/testing/docs/xml/SkiaSharp.Views.Forms/SKCanvasView.xml) | :white_check_mark:Succeeded | |
[docs/xml/SkiaSharp.Views.Forms/SKGLView.xml](https://github.com/mono/SkiaSharp/blob/dev/testing/docs/xml/SkiaSharp.Views.Forms/SKGLView.xml) | :white_check_mark:Succeeded | |
[docs/xml/SkiaSharp/SKAutoCanvasRestore.xml](https://github.com/mono/SkiaSharp/blob/dev/testing/docs/xml/SkiaSharp/SKAutoCanvasRestore.xml) | :white_check_mark:Succeeded | |
[docs/xml/SkiaSharp/SKAutoLockPixels.xml](https://github.com/mono/SkiaSharp/blob/dev/testing/docs/xml/SkiaSharp/SKAutoLockPixels.xml) | :white_check_mark:Succeeded | |
[docs/xml/SkiaSharp/SKAutoMaskFreeImage.xml](https://github.com/mono/SkiaSharp/blob/dev/testing/docs/xml/SkiaSharp/SKAutoMaskFreeImage.xml) | :white_check_mark:Succeeded | |
[docs/xml/SkiaSharp/SKManagedStream.xml](https://github.com/mono/SkiaSharp/blob/dev/testing/docs/xml/SkiaSharp/SKManagedStream.xml) | :white_check_mark:Succeeded | |
[scripts/pipeline.groovy](https://github.com/mono/SkiaSharp/blob/dev/testing/scripts/pipeline.groovy) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C15%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201808151136012978-616%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=SBcldQNDRi7dA0%2BVSXt3Kt7vZG9Qbty8IiXWNwYPni0%3D&st=2018-08-15T11%3A33%3A16Z&se=2018-09-15T11%3A38%3A16Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mattleibow** [comment]
build

**Pull request merged**
