### PR TITLE
Added mouse wheel handling for Forms.UWP

### PR DESCRIPTION
**Pull request by charlenni**
This is for #449. I tried to implement it as easys as possible. I couldn't test it. Didn't get, how to do this.

An alternative would be to use djgtrams suggestions [here](https://forums.xamarin.com/discussion/124185/mouse-wheel-event). He uses Effects to get the wheel events.

> VS bug [#742851](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/742851)

### CODE REVIEW

**Comment by mikekinsman** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Shared/SKTouchEventArgs.cs](https://github.com/charlenni/SkiaSharp/blob/master/source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Shared/SKTouchEventArgs.cs) | :white_check_mark:Succeeded | |
[source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.UWP/SKTouchHandler.cs](https://github.com/charlenni/SkiaSharp/blob/master/source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.UWP/SKTouchHandler.cs) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C6%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201812061339431314-716%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=2L7Rhb84mVemqjPFalkNRx2KG2Q03AooqT1mIHkufLM%3D&st=2018-12-06T13%3A36%3A48Z&se=2019-01-06T13%3A41%3A48Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mattleibow** [comment]
This is good, thanks. I will review and merge.

**Comment by mattleibow** [comment]
I just have a question for Android... I _believe_ that they support mouse... somehow... I did a quick google and saw this: https://stackoverflow.com/questions/11024809/how-can-my-view-respond-to-a-mousewheel

Has anyone ever used a mouse on an Android powered device? Do they even make Android tablets still? Anyway, if anyone has some device that supports mouse and knows something, feel free to comment :)

**Comment by mattleibow** [comment]
I am going to merge. If anyone comes up with an Android with a mouse, I'll add that implementation to Android's code.

**Comment by mikekinsman** [comment]
OPS Build status updates of commit _[80bf244](https://github.com/charlenni/SkiaSharp/pull/716/commits/80bf244723044a3d2a0f8fb8adaecdb426192a7c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Shared/SKTouchEventArgs.cs](https://github.com/charlenni/SkiaSharp/blob/master/source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Shared/SKTouchEventArgs.cs) | :white_check_mark:Succeeded | |
[source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.UWP/SKTouchHandler.cs](https://github.com/charlenni/SkiaSharp/blob/master/source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.UWP/SKTouchHandler.cs) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C14%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201812141916076167-716%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=LsMYpwV2B3QRznDstPji4Ha5xnExebayDEaO7U5qckE%3D&st=2018-12-14T19%3A13%3A23Z&se=2019-01-14T19%3A18%3A23Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
