### PR TITLE
Use Clang for Windows (m79)

### PR DESCRIPTION
**Pull request by mattleibow**
**Description of Change**

Describe your changes here. 

**Bugs Fixed**

- Related to #686
- Related to #1007

Provide links to issues here. Ensure that a GitHub issue was created for your feature or bug fix before sending PR.

**API Changes**

List all API changes here (or just put None), example:

Added: 
 
- `string Class.Property { get; set; }`
- `void Class.Method();`

Changed:

 - `object Cell.OldPropertyName => object Cell.NewPropertyName`

**Behavioral Changes**

Describe any non-bug related behavioral changes that may change how users app behaves when upgrading to this version of the codebase.

**PR Checklist**

- [ ] Has tests (if omitted, state reason in description)
- [ ] Rebased on top of master at time of PR
- [ ] Changes adhere to coding standard
- [ ] Updated documentation

### CODE REVIEW

**Comment by mattleibow** [comment]
This is very weird. I got a 32-bit build locally, now I can't. Seems to have issues with 64-bit and the linker. CI has all sorts of weird issues, and now I have those same issues. How did I get a working build locally? I know it was a real build because I saw a massive change in the performance of drawing. NICE!

**Comment by Gillibald** [comment]
Maybe we should check out the original build file https://github.com/google/skia/blob/master/gn/BUILD.gn

**Comment by mattleibow** [comment]
I don't think I changed anything around clang - I have been trying to make sure I make minimal changes. I updated to Clang 9 and it seemed to build locally. Just updating my agents to that and we shall see. I did a test a local build and ran the benchmarks for #758 - I saw MASSIVE improvements. Instead of taking 50000us, it took 900us - and the unrotated canvas was 200us. I think we got ourselves a winner. As soon as CI is green, then I'll post the binaries here for testing - it is the new version though. And, I'll see what it takes to get the currently released version using clang so we can get these same improvements there.

**Comment by mattleibow** [comment]
Trying to get m68 (the current version) using clang in #1007

**Comment by mattleibow** [comment]
Clang works, so merging all the PRs into branches. 🎉

**Pull request merged**
