### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by mattleibow**

### CODE REVIEW

**Comment by mikekinsman** [comment]
OPS Build status updates of commit _[41f5781](https://github.com/mono/SkiaSharp/pull/737/commits/41f578189f4b4742b76d29a96fbd854be7f16175)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 52 sec(s)_

**Comment by mikekinsman** [comment]
OPS Build status updates of commit _[41f5781](https://github.com/mono/SkiaSharp/pull/737/commits/41f578189f4b4742b76d29a96fbd854be7f16175)_: 

:clock10: **Full build**: average full build time is not available, there is no data for this repository.

> Note: A full build takes more time than an incremental build.  This is the expected behavior of the build system.

**Comment by mikekinsman** [comment]
OPS Build status updates of commit _[41f5781](https://github.com/mono/SkiaSharp/pull/737/commits/41f578189f4b4742b76d29a96fbd854be7f16175)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.github/ISSUE_TEMPLATE/bug-report.md](https://github.com/mono/SkiaSharp/blob/dev/templates/.github/ISSUE_TEMPLATE/bug-report.md) | :white_check_mark:Succeeded | |
[.github/ISSUE_TEMPLATE/bug_report.md](https://github.com/mono/SkiaSharp/blob/dev/templates/.github/ISSUE_TEMPLATE/bug_report.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C18%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201812180710250818-737%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=cjHU0jJ8sCku%2Bk6Nc4nf6bW69zYgWr7UMOCfEVEbnvs%3D&st=2018-12-18T07%3A09%3A24Z&se=2019-01-18T07%3A14%3A24Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
OPS Build status updates of commit _[8637e1d](https://github.com/mono/SkiaSharp/pull/737/commits/8637e1dd48169153a27a690679ff337607a92761)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 52 sec(s)_

**Comment by mikekinsman** [comment]
OPS Build status updates of commit _[8637e1d](https://github.com/mono/SkiaSharp/pull/737/commits/8637e1dd48169153a27a690679ff337607a92761)_: 

:clock10: **Full build**: average full build time is _1 min(s) 34 sec(s)_ [calculated from last _1_ build(s)]

> Note: A full build takes more time than an incremental build.  This is the expected behavior of the build system.

**Comment by mikekinsman** [comment]
OPS Build status updates of commit _[8637e1d](https://github.com/mono/SkiaSharp/pull/737/commits/8637e1dd48169153a27a690679ff337607a92761)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.github/ISSUE_TEMPLATE/bug-report.md](https://github.com/mono/SkiaSharp/blob/dev/templates/.github/ISSUE_TEMPLATE/bug-report.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C18%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201812180711051745-737%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=11fu7qpbh1K5RFxRFDjyg3iWHiea%2Ba7FEpw0kHLghhk%3D&st=2018-12-18T07%3A12%3A45Z&se=2019-01-18T07%3A17%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
OPS Build status updates of commit _[f7f0066](https://github.com/mono/SkiaSharp/pull/737/commits/f7f0066f773527132470b6144c1fec50493f9d29)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 52 sec(s)_

**Comment by mattleibow** [comment]
build

**Pull request merged**
