### PR TITLE
[WIP] Optional GPU

### PR DESCRIPTION
**Pull request by mattleibow**
Linux build can now produce a non-GPU .so. Right now this part is working, but the configuration needs love. (basically, all the linux configuration needs love)

This must be merged first: https://github.com/mono/skia/pull/49

Related to https://github.com/mono/SkiaSharp/issues/90

### CODE REVIEW

**Comment by kekekeks** [comment]
I'm pretty sure that it's possible to keep GPU support without referencing libGL/libGLU/libX11 by exposing `GrGLAssemble*Interface`: https://github.com/mono/skia/blob/xamarin-mobile-bindings/include/gpu/gl/GrGLAssembleInterface.h#L17

**Comment by kekekeks** [comment]
That way skia will obtain references to OpenGL functions using user-provided glGetProcAddress

**Comment by kekekeks** [comment]
BTW, GLX won't be present in "pure" Wayland/Mir environment, they use EGL instead.

**Comment by mattleibow** [comment]
@kekekeks Thanks for the work, I will get it all merged. BTW, I already expose the `GRGLAssemble*Interface` members on the `GRGlInterface` type in SkiaSharp - that is actually how I do the ANGLE bits on UWP.

Doing it vial assemble is better than having no support at all. Good point.

**Pull request merged**
