### PR TITLE
Added Path Effects

### PR DESCRIPTION
**Pull request by mattleibow**
This is the code for issue #47

### CODE REVIEW

**Comment by migueldeicaza** [comment]
LOVE IT!

**Comment by bholmes** [comment]
I am not seeing ref and unref calls on the new SKEffect object.  What is keeping the object alive or causing it to be cleaned up?

**Comment by migueldeicaza** [comment]
@bholmes it inherits the Finalizer/Disposer from SKObject which has the unref, and the object creation creates the objects with refcount=1

**Comment by mattleibow** [comment]
@migueldeicaza In this case, @bholmes is right because `SKObject` does not have the unref. This is because not all SKObjects are `SKRefCnt` objects. An example would be `SKBitmap`/`SKPaint`, which is just a plain object and the destructor is used.

I think there are just those two variants, so I could create another type that uses the unref and the base uses the destructor, but for simplicity's sake, I just unref in the dispose methods. So, in this case, I forgot to add the unref, which I have added now.

**Comment by bholmes** [comment]
@mattleibow we can merge this when you are ready.  I know you are working on a new version + upstreaming changes.  So I will let you decide when is the best time to merge.

**Comment by mattleibow** [comment]
I am merging this in #116

**Pull request closed without merging**
