### PR TITLE
Add support for SKXamlCanvas on Uno Platform SkiaSharp backends

### PR DESCRIPTION
**Pull request by jeromelaban**
**Description of Change**

Add support for `SKXamlCanvas` on Uno Platform SkiaSharp backends, by using software rendering onto an off-screen surface.

While the `SKSwapChainPanel` is present (as it is part of the reference API shared with WebAssembly), it is currently not implemented.

In order to support this change, the `SKXamlCanvas` which was incorrectly inheriting from `FrameworkElement`, is now inheriting from `Canvas`, which exposes the `Background` property. **It is a breaking change**, but all the properties of `FrameworkElement` are also present on `Canvas`, which will not break existing code.

Note that non-breaking fixes are needed in Uno for this change to work properly (https://github.com/unoplatform/uno/pull/5266), those will be included as part of Uno 3.5.x and 3.6.

**API Changes**

Changed:

 - `SKXamlCanvas : FrameworkElement` -> `SKXamlCanvas : Canvas`

**Behavioral Changes**

None.

**PR Checklist**

- [ ] Has tests (if omitted, state reason in description)
- [x] Rebased on top of main at time of PR
- [x] Changes adhere to coding standard
- [x] Updated documentation

### CODE REVIEW

**Comment by jeromelaban** [comment]
Looks like the rebuild passed most of the tests :) The rest is likely azure devops security from forks. @mattleibow Is there something I can help you with ?

**Comment by mattleibow** [comment]
Sorry about the incredibly delay, MAUI was a bit of beast :)

Is it possible to add a sample for the Skia backends? Only has to be a basic sample in say `samples\Basic\Uno\SkiaSharpSample.Xxx`? The WASM sample probably will be the easiest to copy for the targets and props - if they are needed.

I notice there is a targets file to set the `UnoRuntimeEnabledPackage` property. If one is needed (very likely if I understand), then just move it to the `source\SkiaSharp.Views.Uno\SkiaSharp.Views.Uno` folder and link both WASM and the skia backends to copy it. That way all the samples can get it instead of having to build a specific one.

Now that I got some time, I hope to merge this and release a preview.

**Comment by jeromelaban** [comment]
@mattleibow do you know what the build errors are ? I'd guess it's fork-related authorizations :)

**Comment by MaksimNikonovOrioninc** [comment]
@mattleibow Is it possible to approve this pool request? our team are waiting for that!

**Comment by jeromelaban** [comment]
Closing in favor of https://github.com/mono/SkiaSharp/pull/1704

**Pull request closed without merging**
