### PR TITLE
Build Native Linux on Ubuntu 14 with Clang

### PR DESCRIPTION
**Pull request by mattleibow**
There appears to be some major performance boosts with `clang` (#686), so I am trying out a build for that. And, I am going to drop the version of Ubuntu used for building to 14.04 for increased compatibility with older Linux distros.

 - [x] switch to clang
 - [x] use Ubuntu 14
 - [x] statically link libstdc++ and libgcc

> VS bug [#777658](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/777658)

### CODE REVIEW

**Comment by mikekinsman** [comment]
OPS Build status updates of commit _[82c572e](https://github.com/mono/SkiaSharp/pull/767/commits/82c572e907fe642236f19fd7b0e2bdda36a3b222)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 59 sec(s)_

**Comment by mikekinsman** [comment]
OPS Build status updates of commit _[82c572e](https://github.com/mono/SkiaSharp/pull/767/commits/82c572e907fe642236f19fd7b0e2bdda36a3b222)_: 

:clock10: **Incremental building**: average incremental building time is _20 sec(s)_

**Comment by mikekinsman** [comment]
OPS Build status updates of commit _[82c572e](https://github.com/mono/SkiaSharp/pull/767/commits/82c572e907fe642236f19fd7b0e2bdda36a3b222)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[scripts/pipeline.groovy](https://github.com/mono/SkiaSharp/blob/dev/ubuntu14/scripts/pipeline.groovy) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C24%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201901240036117346-767%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Fg8auBALDp%2B9xKmPBOOZCNRwAgHqpG7IlmS8s16G004%3D&st=2019-01-24T00%3A33%3A32Z&se=2019-02-24T00%3A38%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
OPS Build status updates of commit _[99338be](https://github.com/mono/SkiaSharp/pull/767/commits/99338bef67e291a445505ca323c90c530d37752b)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 59 sec(s)_

**Comment by mikekinsman** [comment]
OPS Build status updates of commit _[99338be](https://github.com/mono/SkiaSharp/pull/767/commits/99338bef67e291a445505ca323c90c530d37752b)_: 

:clock10: **Incremental building**: average incremental building time is _20 sec(s)_

**Comment by mikekinsman** [comment]
OPS Build status updates of commit _[99338be](https://github.com/mono/SkiaSharp/pull/767/commits/99338bef67e291a445505ca323c90c530d37752b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[cake/BuildExternals.cake](https://github.com/mono/SkiaSharp/blob/dev/ubuntu14/cake/BuildExternals.cake) | :white_check_mark:Succeeded | |
[scripts/build-linux.sh](https://github.com/mono/SkiaSharp/blob/dev/ubuntu14/scripts/build-linux.sh) | :white_check_mark:Succeeded | |
[scripts/pipeline.groovy](https://github.com/mono/SkiaSharp/blob/dev/ubuntu14/scripts/pipeline.groovy) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C24%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201901240201403002-767%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=g%2FQHpQyFLk4D63EY2YAhA2fXwZZdcT09qF71MRKB3GU%3D&st=2019-01-24T01%3A59%3A02Z&se=2019-02-24T02%3A04%3A02Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mattleibow** [comment]
build

**Comment by mikekinsman** [comment]
OPS Build status updates of commit _[a4c2199](https://github.com/mono/SkiaSharp/pull/767/commits/a4c21993bd8230c8555ed3e8732acc5597c9290a)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 59 sec(s)_

**Comment by mikekinsman** [comment]
OPS Build status updates of commit _[a4c2199](https://github.com/mono/SkiaSharp/pull/767/commits/a4c21993bd8230c8555ed3e8732acc5597c9290a)_: 

:clock10: **Incremental building**: average incremental building time is _20 sec(s)_

**Comment by mikekinsman** [comment]
OPS Build status updates of commit _[a4c2199](https://github.com/mono/SkiaSharp/pull/767/commits/a4c21993bd8230c8555ed3e8732acc5597c9290a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[cake/BuildExternals.cake](https://github.com/mono/SkiaSharp/blob/dev/ubuntu14/cake/BuildExternals.cake) | :white_check_mark:Succeeded | |
[scripts/build-linux.sh](https://github.com/mono/SkiaSharp/blob/dev/ubuntu14/scripts/build-linux.sh) | :white_check_mark:Succeeded | |
[scripts/pipeline.groovy](https://github.com/mono/SkiaSharp/blob/dev/ubuntu14/scripts/pipeline.groovy) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C24%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201901241421500795-767%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=FFUAA8lrfvblXE2ng%2Fb%2Bp22qEGEGi5htbgpmyO%2By1A4%3D&st=2019-01-24T14%3A19%3A10Z&se=2019-02-24T14%3A24%3A10Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
OPS Build status updates of commit _[ff66cb9](https://github.com/mono/SkiaSharp/pull/767/commits/ff66cb92f39acb2f04ed1e6bf548ef4621bf19b9)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 59 sec(s)_

**Comment by mikekinsman** [comment]
OPS Build status updates of commit _[ff66cb9](https://github.com/mono/SkiaSharp/pull/767/commits/ff66cb92f39acb2f04ed1e6bf548ef4621bf19b9)_: 

:clock10: **Incremental building**: average incremental building time is _19 sec(s)_

**Comment by mikekinsman** [comment]
OPS Build status updates of commit _[ff66cb9](https://github.com/mono/SkiaSharp/pull/767/commits/ff66cb92f39acb2f04ed1e6bf548ef4621bf19b9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[cake/BuildExternals.cake](https://github.com/mono/SkiaSharp/blob/dev/ubuntu14/cake/BuildExternals.cake) | :white_check_mark:Succeeded | |
[scripts/build-linux.sh](https://github.com/mono/SkiaSharp/blob/dev/ubuntu14/scripts/build-linux.sh) | :white_check_mark:Succeeded | |
[scripts/pipeline.groovy](https://github.com/mono/SkiaSharp/blob/dev/ubuntu14/scripts/pipeline.groovy) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C24%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201901241601037000-767%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=CSiAlThHMiFHi27JrtWhBjqEcH5ZERna3tgsDcSHvXo%3D&st=2019-01-24T15%3A58%3A42Z&se=2019-02-24T16%3A03%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
OPS Build status updates of commit _[3a0400c](https://github.com/mono/SkiaSharp/pull/767/commits/3a0400cea1bacbec0ed44bde1135dc63e5061256)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 59 sec(s)_

**Comment by mikekinsman** [comment]
OPS Build status updates of commit _[3a0400c](https://github.com/mono/SkiaSharp/pull/767/commits/3a0400cea1bacbec0ed44bde1135dc63e5061256)_: 

:clock10: **Incremental building**: average incremental building time is _19 sec(s)_

**Comment by mikekinsman** [comment]
OPS Build status updates of commit _[3a0400c](https://github.com/mono/SkiaSharp/pull/767/commits/3a0400cea1bacbec0ed44bde1135dc63e5061256)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[cake/BuildExternals.cake](https://github.com/mono/SkiaSharp/blob/dev/ubuntu14/cake/BuildExternals.cake) | :white_check_mark:Succeeded | |
[scripts/build-linux.sh](https://github.com/mono/SkiaSharp/blob/dev/ubuntu14/scripts/build-linux.sh) | :white_check_mark:Succeeded | |
[scripts/pipeline.groovy](https://github.com/mono/SkiaSharp/blob/dev/ubuntu14/scripts/pipeline.groovy) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C24%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201901241616303399-767%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2BvUijCG4dN%2Bbwcv4%2F8uKllwavTFo0Wk6aXQrDXOJXXs%3D&st=2019-01-24T16%3A13%3A53Z&se=2019-02-24T16%3A18%3A53Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mattleibow** [comment]
build

**Comment by mattleibow** [comment]
Build

**Comment by mikekinsman** [comment]
OPS Build status updates of commit _[6ffc46f](https://github.com/mono/SkiaSharp/pull/767/commits/6ffc46feb335a5ef073b5abefc77258616e6580f)_: 

:clock10: **Preparing**: average preparing time is _2 min(s) 1 sec(s)_

**Comment by mikekinsman** [comment]
OPS Build status updates of commit _[6ffc46f](https://github.com/mono/SkiaSharp/pull/767/commits/6ffc46feb335a5ef073b5abefc77258616e6580f)_: 

:clock10: **Incremental building**: average incremental building time is _19 sec(s)_

**Comment by mikekinsman** [comment]
OPS Build status updates of commit _[6ffc46f](https://github.com/mono/SkiaSharp/pull/767/commits/6ffc46feb335a5ef073b5abefc77258616e6580f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[cake/BuildExternals.cake](https://github.com/mono/SkiaSharp/blob/dev/ubuntu14/cake/BuildExternals.cake) | :white_check_mark:Succeeded | |
[scripts/build-linux.sh](https://github.com/mono/SkiaSharp/blob/dev/ubuntu14/scripts/build-linux.sh) | :white_check_mark:Succeeded | |
[scripts/pipeline.groovy](https://github.com/mono/SkiaSharp/blob/dev/ubuntu14/scripts/pipeline.groovy) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C1%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201902011153123420-767%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=3frCtrylSq1RYHrBC5ZIaw5A4r5JehNwMXYbo6WXwJU%3D&st=2019-02-01T11%3A50%3A52Z&se=2019-03-04T11%3A55%3A52Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
