### PR TITLE
Add Metal APIs

### LINKED ISSUE #1391: [FEATURE] Metal APIs
**Is your feature request related to a problem? Please describe.**
We need to add the metal APIs available on Apple hardware.

### PR DESCRIPTION
**Pull request by mattleibow**
**Description of Change**

First look at adding the APIs to work with Metal.

**Bugs Fixed**

- Fixes #1391 

**API Changes**

List all API changes here (or just put None), example:

Added: 
 
- `string Class.Property { get; set; }`
- `void Class.Method();`

Changed:

 - `object Cell.OldPropertyName => object Cell.NewPropertyName`

**Behavioral Changes**

Describe any non-bug related behavioral changes that may change how users app behaves when upgrading to this version of the codebase.

**PR Checklist**

- [ ] Has tests (if omitted, state reason in description)
- [ ] Rebased on top of master at time of PR
- [ ] Changes adhere to coding standard
- [ ] Updated documentation

### CODE REVIEW

**Comment by mattleibow** [comment]
This is just hacky right now, but I think I m doing it wrong as it crashes when creating the surface. I think I am not working with the objc objects correctly.

**Comment by mattleibow** [comment]
Fixed that crash... was passing a struct off as a field in that struct, darned `void*` accepting everything.

**Comment by nor0x** [comment]
hi @mattleibow 👋
could you update me on the status of the Metal APIs? My current project could really benefit of Metal support and i would be happy to help with this PR

Thanks!

**Comment by mattleibow** [comment]
@nor0x I was waiting to see what would happen with the API as the new versions. So far it looks safe. Just waiting on another test PR to build: https://github.com/mono/SkiaSharp/pull/1598

If that is mostly green then I might just merge.

**Comment by AnarchyMob** [comment]
Hello, do you know how things are with the Direct3D backend in 88 milestone?

**Comment by mattleibow** [comment]
@AnarchyMob I have a PR for m88 at #1596 

I have not tested the D3D yet as that is just an update of the current set of APIs. You can also ask all about the support level and feature set on the skia forums: https://groups.google.com/g/skia-discuss

I think we are still in an early stage of D3D, but I need to confirm. However, I think things are mostly working. A bit unsure here...

**Pull request merged**
