### PR TITLE
Added missing functions for SKPath

### PR DESCRIPTION
**Pull request by charlenni**
Added missing functions for SKPath:
- Reset()
- Rewind()
Added to SKPath.cs and SkiaAPI.cs in same style as SKPath.Close()

### CODE REVIEW

**Comment by tdenniston** [comment]
Looks like you have some whitespacing issues: this project uses hard tabs.

**Comment by mattleibow** [comment]
Thanks for this @charlenni, I am looking to merge this, but I can't find the native `sk_path_reset` and `sk_path_rewind` methods. Did you forget to PR the mono/skia repo?

Just a note on the whitespacing there - it uses spaces, not tabs :)

**Comment by charlenni** [comment]
Sorry for the delay. 

The changes to SkiaAPI.cs are added to the PR and mono/skia already contains this functions. Or I'm missing something?

**Comment by migueldeicaza** [comment]
It does not look like the code in Skia has it yet:

https://github.com/mono/skia/blob/xamarin-mobile-bindings/src/c/xamarin/sk_x_path.cpp

**Comment by migueldeicaza** [comment]
I implemented the Skia counterpart.

**Pull request merged**
