### PR TITLE
Updating native skia to m67

### PR DESCRIPTION
**Pull request by mattleibow**

### CODE REVIEW

**Comment by mikekinsman** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** File:../externals/skia not existed.
 - **[Error]** Some error ocurred while parsing changelist file: W:\at0t-log-3df66449\change-list-with-redirection.mapped.tsv.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C7%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201807072212300169-570%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=NOrVUEfjxndvDprefLMLD5M3OhSCGWFF7Vq2GpGmj%2Fk%3D&st=2018-07-07T22%3A09%3A27Z&se=2018-08-07T22%3A14%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** File:../externals/skia not existed.
 - **[Error]** Some error ocurred while parsing changelist file: W:\anvr-log-78211641\change-list-with-redirection.mapped.tsv.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C12%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201807121133184140-570%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=7qAJHgt6fcpsIIGEM4b%2BQM1mgrVN8JFsEkPZwn3eEMM%3D&st=2018-07-12T11%3A30%3A32Z&se=2018-08-12T11%3A35%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** File:../externals/skia not existed.
 - **[Error]** Some error ocurred while parsing changelist file: W:\br35-log-fd3dd27b\change-list-with-redirection.mapped.tsv.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C12%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201807121500423995-570%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=U6GxJcvEIvyDOUsgar0dsMhibul95ugOz5G1Z1aC1jQ%3D&st=2018-07-12T14%3A57%3A30Z&se=2018-08-12T15%3A02%3A30Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** File:../externals/skia not existed.
 - **[Error]** Some error ocurred while parsing changelist file: W:\xivu-log-e0ed5a61\change-list-with-redirection.mapped.tsv.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C16%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201807162328034242-570%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=JALeaG3xCEpeNiuB5%2BTSAXJvBVuh0t2mVrIGxT0bMck%3D&st=2018-07-16T23%3A25%3A00Z&se=2018-08-16T23%3A30%3A00Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** File:../externals/skia not existed.
 - **[Error]** Some error ocurred while parsing changelist file: W:\kqvj-log-35d14608\change-list-with-redirection.mapped.tsv.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C17%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201807171248567131-570%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=MQi23FPaVscObyJIsAcR4w%2BfBfg%2FuvQkhkkFDhFT9qY%3D&st=2018-07-17T12%3A46%3A11Z&se=2018-08-17T12%3A51%3A11Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** File:../externals/skia not existed.
 - **[Error]** Some error ocurred while parsing changelist file: W:\yk55-log-7d3a52e3\change-list-with-redirection.mapped.tsv.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C17%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201807171900516974-570%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=coaabW1gocLV5WazLE2ocwbAxZpmTB2lrIu%2BFLNHcFQ%3D&st=2018-07-17T18%3A57%3A47Z&se=2018-08-17T19%3A02%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** File:../externals/skia not existed.
 - **[Error]** Some error ocurred while parsing changelist file: W:\kvaq-log-0c610bb9\change-list-with-redirection.mapped.tsv.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C17%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201807171903526378-570%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=oQj502KweR7Cav7QhmRfTT%2B6eGAuGBSwCr3Aapm32F0%3D&st=2018-07-17T19%3A00%3A46Z&se=2018-08-17T19%3A05%3A46Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** File:../externals/skia not existed.
 - **[Error]** Some error ocurred while parsing changelist file: W:\mc0o-log-ae752e6b\change-list-with-redirection.mapped.tsv.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C18%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201807180159394571-570%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=JM%2BurSQPmPWQ%2BBTYsC5I2NN5Dory72kwf4xf8D2o0eg%3D&st=2018-07-18T01%3A56%3A36Z&se=2018-08-18T02%3A01%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** File:../externals/skia not existed.
 - **[Error]** Some error ocurred while parsing changelist file: W:\lruo-log-119d2e1a\change-list-with-redirection.mapped.tsv.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C18%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201807181532529518-570%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=wgpM70lSGderaSSw2FuMjOdMoCzmDco4Fo4QeTBDUhs%3D&st=2018-07-18T15%3A29%3A52Z&se=2018-08-18T15%3A34%3A52Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** File:../externals/skia not existed.
 - **[Error]** Some error ocurred while parsing changelist file: W:\lzlb-log-74c43b1e\change-list-with-redirection.mapped.tsv.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C18%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201807181556528756-570%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=T6BFivskzQyrpdxLZqY9GSX2YLC1sYN%2Fxy2iyH3QuWw%3D&st=2018-07-18T15%3A53%3A49Z&se=2018-08-18T15%3A58%3A49Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** File:../externals/skia not existed.
 - **[Error]** Some error ocurred while parsing changelist file: W:\gw3j-log-6904d071\change-list-with-redirection.mapped.tsv.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C18%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201807181615212192-570%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=bgb1YTy1aHsk8oNrp1iX2Lkczt%2F8kAZ5qn0Oz9QJPFo%3D&st=2018-07-18T16%3A12%3A18Z&se=2018-08-18T16%3A17%3A18Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** File:../externals/skia not existed.
 - **[Error]** Some error ocurred while parsing changelist file: W:\kzov-log-78e347c6\change-list-with-redirection.mapped.tsv.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C18%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201807181654218672-570%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=MfXy4nHe9FzCbZsLdFhNv%2B03Qb%2BMPIQ3CEk2WQLJKbg%3D&st=2018-07-18T16%3A51%3A20Z&se=2018-08-18T16%3A56%3A20Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** File:../externals/skia not existed.
 - **[Error]** Some error ocurred while parsing changelist file: W:\q3m2-log-032ad79a\change-list-with-redirection.mapped.tsv.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C18%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201807181714431495-570%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Vira71tXB%2ByB4jeAzoMVwXE%2B%2BEF1fzfjkg8EqR53sTQ%3D&st=2018-07-18T17%3A11%3A59Z&se=2018-08-18T17%3A16%3A59Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** File:../externals/skia not existed.
 - **[Error]** Some error ocurred while parsing changelist file: W:\0kp1-log-77c11f0b\change-list-with-redirection.mapped.tsv.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C18%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201807181734591107-570%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=I2Iw%2FaHnufzn%2Fkfb4z2MLmT3Obqpr5c3ivj1cugcgA4%3D&st=2018-07-18T17%3A31%3A54Z&se=2018-08-18T17%3A36%3A54Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** File:../externals/skia not existed.
 - **[Error]** Some error ocurred while parsing changelist file: W:\ich3-log-b4a72690\change-list-with-redirection.mapped.tsv.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C18%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201807182118164543-570%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=TN5Cqbbsewb6pKBMjyk%2BNMuIb%2FXFMHAFIWREHkeTPWE%3D&st=2018-07-18T21%3A15%3A36Z&se=2018-08-18T21%3A20%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** File:../externals/skia not existed.
 - **[Error]** Some error ocurred while parsing changelist file: W:\3md3-log-3fd57540\change-list-with-redirection.mapped.tsv.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C18%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201807182155587072-570%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=sqk9iDKne7v2QRibKir%2FxYQ%2B46nd0he3MvIPibYz6yM%3D&st=2018-07-18T21%3A52%3A55Z&se=2018-08-18T21%3A57%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** File:../externals/skia not existed.
 - **[Error]** Some error ocurred while parsing changelist file: W:\xw3w-log-26e0d8ba\change-list-with-redirection.mapped.tsv.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C19%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201807190028426391-570%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=VFQ%2Fm%2FCX%2FfEF%2BT8UMVS6Joif1f3Rrkds5SWNFyVW1QI%3D&st=2018-07-19T00%3A26%3A02Z&se=2018-08-19T00%3A31%3A02Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Prepare of repository data failed. Proposal: Please check if there&#39;re files with same name but only different in casing for the following path: binding/HarfBuzzSharp.Android/HarfBuzzSharp.Android.csproj,binding/HarfBuzzSharp.OSX/HarfBuzzSharp.OSX.csproj,binding/HarfBuzzSharp.Tizen/HarfBuzzSharp.Tizen.csproj,binding/HarfBuzzSharp.iOS/HarfBuzzSharp.iOS.csproj,binding/HarfBuzzSharp.tvOS/HarfBuzzSharp.tvOS.csproj,binding/SkiaSharp.Tizen/SkiaSharp.Tizen.csproj,source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Mac/SkiaSharp.Views.Forms.Mac.csproj,source/SkiaSharp.Workbooks/SkiaSharp.Workbooks.csproj in your repository.. After fix, please try the build again.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C19%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201807192201163064-570%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=SIL3CeSGx8uikeRyOLSFy8WB%2BSFFkNdJAQ3iqjM52eY%3D&st=2018-07-19T21%3A56%3A45Z&se=2018-08-19T22%3A01%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Prepare of repository data failed. Proposal: Please check if there&#39;re files with same name but only different in casing for the following path: binding/HarfBuzzSharp.Android/HarfBuzzSharp.Android.csproj,binding/HarfBuzzSharp.OSX/HarfBuzzSharp.OSX.csproj,binding/HarfBuzzSharp.Tizen/HarfBuzzSharp.Tizen.csproj,binding/HarfBuzzSharp.iOS/HarfBuzzSharp.iOS.csproj,binding/HarfBuzzSharp.tvOS/HarfBuzzSharp.tvOS.csproj,binding/SkiaSharp.Tizen/SkiaSharp.Tizen.csproj,source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Mac/SkiaSharp.Views.Forms.Mac.csproj,source/SkiaSharp.Workbooks/SkiaSharp.Workbooks.csproj in your repository.. After fix, please try the build again.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C20%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201807200826421879-570%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=LmiuG%2FXAstsl2e88JUDzSxJUFedoct7srTacGNH5zlA%3D&st=2018-07-20T08%3A22%3A02Z&se=2018-08-20T08%3A27%3A02Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Prepare of repository data failed. Proposal: Please check if there&#39;re files with same name but only different in casing for the following path: binding/HarfBuzzSharp.Android/HarfBuzzSharp.Android.csproj,binding/HarfBuzzSharp.OSX/HarfBuzzSharp.OSX.csproj,binding/HarfBuzzSharp.Tizen/HarfBuzzSharp.Tizen.csproj,binding/HarfBuzzSharp.iOS/HarfBuzzSharp.iOS.csproj,binding/HarfBuzzSharp.tvOS/HarfBuzzSharp.tvOS.csproj,binding/SkiaSharp.Tizen/SkiaSharp.Tizen.csproj,source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Mac/SkiaSharp.Views.Forms.Mac.csproj,source/SkiaSharp.Workbooks/SkiaSharp.Workbooks.csproj in your repository.. After fix, please try the build again.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C20%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201807200922473087-570%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ntLyiu7e58knEnVLYyjhFq12nVX001%2BKf1x%2BkvrOu5Q%3D&st=2018-07-20T09%3A18%3A07Z&se=2018-08-20T09%3A23%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Prepare of repository data failed. Proposal: Please check if there&#39;re files with same name but only different in casing for the following path: binding/HarfBuzzSharp.Android/HarfBuzzSharp.Android.csproj,binding/HarfBuzzSharp.OSX/HarfBuzzSharp.OSX.csproj,binding/HarfBuzzSharp.Tizen/HarfBuzzSharp.Tizen.csproj,binding/HarfBuzzSharp.iOS/HarfBuzzSharp.iOS.csproj,binding/HarfBuzzSharp.tvOS/HarfBuzzSharp.tvOS.csproj,binding/SkiaSharp.Tizen/SkiaSharp.Tizen.csproj,source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Mac/SkiaSharp.Views.Forms.Mac.csproj,source/SkiaSharp.Workbooks/SkiaSharp.Workbooks.csproj in your repository.. After fix, please try the build again.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C20%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201807201449275252-570%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=DttgkOYJkXw7d2iq7wBLn2tGqknbL9r4bYncnjS9Bak%3D&st=2018-07-20T14%3A44%3A46Z&se=2018-08-20T14%3A49%3A46Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Prepare of repository data failed. Proposal: Please check if there&#39;re files with same name but only different in casing for the following path: binding/HarfBuzzSharp.Android/HarfBuzzSharp.Android.csproj,binding/HarfBuzzSharp.OSX/HarfBuzzSharp.OSX.csproj,binding/HarfBuzzSharp.Tizen/HarfBuzzSharp.Tizen.csproj,binding/HarfBuzzSharp.iOS/HarfBuzzSharp.iOS.csproj,binding/HarfBuzzSharp.tvOS/HarfBuzzSharp.tvOS.csproj,binding/SkiaSharp.Tizen/SkiaSharp.Tizen.csproj,source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Mac/SkiaSharp.Views.Forms.Mac.csproj,source/SkiaSharp.Workbooks/SkiaSharp.Workbooks.csproj in your repository.. After fix, please try the build again.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C21%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201807212051490650-570%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=4L2uT6Zd3z79x0d5ISyEZHZCQEv7xQBzheO5tGdZSUs%3D&st=2018-07-21T20%3A47%3A08Z&se=2018-08-21T20%3A52%3A08Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Prepare of repository data failed. Proposal: Please check if there&#39;re files with same name but only different in casing for the following path: binding/HarfBuzzSharp.tvOS/HarfBuzzSharp.tvOS.csproj,binding/SkiaSharp.Tizen/SkiaSharp.Tizen.csproj,source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Mac/SkiaSharp.Views.Forms.Mac.csproj,source/SkiaSharp.Workbooks/SkiaSharp.Workbooks.csproj in your repository.. After fix, please try the build again.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C21%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201807212304522646-570%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=LKRSaiNOy6asWPMR%2BTuWMdA%2BprgqB5iwmG%2FV6J9Wr8I%3D&st=2018-07-21T23%3A00%3A14Z&se=2018-08-21T23%3A05%3A14Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/mono/SkiaSharp, working directory: W:\4hvy-s, target branch: master, target branch commit: 8085c9f7662f29fa56815593831b530834fe597e, source branch: dev/update-m67, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C23%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201807232143508571-570%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=1syN8ziCAFWW4gEYXjDwR5dOtEpwY9MCYO1JH4BWpE0%3D&st=2018-07-23T21%3A39%3A03Z&se=2018-08-23T21%3A44%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/mono/SkiaSharp, working directory: W:\kjvn-s, target branch: master, target branch commit: 8085c9f7662f29fa56815593831b530834fe597e, source branch: dev/update-m67, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C23%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201807232317426224-570%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Ze1cKSOxWYWtKlsLTT13VC4hKj8bumCMma8tpk3XD94%3D&st=2018-07-23T23%3A12%3A54Z&se=2018-08-23T23%3A17%3A54Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** File:../externals/skia not existed.
 - **[Error]** Some error ocurred while parsing changelist file: W:\ybry-log-33195f03\change-list-with-redirection.mapped.tsv.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C24%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201807240150030048-570%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=TOJzQo2lW3RJ%2BgVA%2BUsQXXCC8uZf3OhTP%2BTBVsHzSAo%3D&st=2018-07-24T01%3A46%3A41Z&se=2018-08-24T01%3A51%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mattleibow** [comment]
build

**Comment by mikekinsman** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** File:../externals/skia not existed.
 - **[Error]** Some error ocurred while parsing changelist file: W:\loa3-log-572a6371\change-list-with-redirection.mapped.tsv.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C26%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201807261547155469-570%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=GZOi3KDlbCQVUSKJCJoF1PuneQGvVTNH%2FZIfW1mP1Nw%3D&st=2018-07-26T15%3A43%3A56Z&se=2018-08-26T15%3A48%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
