### PR TITLE
Use Clang for Windows (m68)

### LINKED ISSUE #758: SKCanvas rendering rotated image very slow compared to System.Drawing (4x slower)
Rendering a rotated bitmap with SKCanvas is slow, compared with System.Drawing (4x slower)
See below code, it produces following output:
rotation: 20°
Skia: 6860ms
System.Drawing: 1643ms

           float rotation = 20;
            Console.WriteLine("rotation: "+rotation+"°");

            // Skia part...
            MemoryStream imageStream = new MemoryStream(new WebClient().DownloadData(@"https://via.placeholder.com/450"));
            SKBitmap skBitmapToBlit = SKBitmap.Decode(imageStream);
            SKBitmap renderSkBitmap = new SKBitmap(512, 512, isOpaque: false);
            SKCanvas canvas = new SKCanvas(renderSkBitmap);
            SKPaint paint = new SKPaint()
            {
                FilterQuality = SKFilterQuality.High
            };
            canvas.RotateDegrees(rotation);
            var sw = Stopwatch.StartNew();
            for (int i=0; i<100; i++)
            {             
                canvas.DrawBitmap(skBitmapToBlit, new SKPoint(10, 10), paint);
            };
            Console.WriteLine("Skia: "+sw.ElapsedMilliseconds + "ms");

            // System.Drawing part...
            imageStream = new MemoryStream(new WebClient().DownloadData(@"https://via.placeholder.com/450"));
            Bitmap gdiBitmapToBlit = new Bitmap(imageStream);
            Bitmap renderGdiBitmap = new Bitmap(512, 512, System.Drawing.Imaging.PixelFormat.Format32bppArgb);
            Graphics graphics = Graphics.FromImage(renderGdiBitmap);
            graphics.InterpolationMode = System.Drawing.Drawing2D.InterpolationMode.Bicubic;
            graphics.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.HighSpeed;
            var matrix = new Matrix();
            matrix.Rotate(rotation);
            graphics.Transform=matrix;
            sw = Stopwatch.StartNew();
            for (int i = 0; i < 100; i++)
            {
                graphics.DrawImage(gdiBitmapToBlit, new PointF(10, 10));
            };
            Console.WriteLine("System.Drawing: " + sw.ElapsedMilliseconds + "ms");

Note that, without rotating, Skia is much faster than System.Drawing (36x faster).

Symptom : Skia 4x slower than System.Drawing, with provided code.
Expected : Skia faster than System.Drawing, with provided code.

- Version with issue:  1.68.0
- Last known good version:  N/A
- IDE:  Visual Studio
- Platform Target Frameworks: .net framework 4.7

> VS bug [#776803](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/776803)

### PR DESCRIPTION
**Pull request by mattleibow**
**Description of Change**

Switch to using Clang 9 instead of MSVC for Win32 builds.

**Bugs Fixed**

- Resolves #758 
- Related to #686 

**API Changes**

None.

**Behavioral Changes**

There shouldn't be any visible _changes_ except for performance improvements. Google has been optimizing skia for Clang, and as a result the MSVC binaries are significantly slower. With this PR, we are using Clang on Windows desktop/Win32 so we get all those improvements now.

UWP is still using MSVC, but that will be changed at a later stage.

**PR Checklist**

- [x] Has tests (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Updated documentation

### CODE REVIEW

**Comment by TabishRafiq** [comment]
Hello mattleibow,

Thank you for all these, I still curious to know who can I compile C# application using clang?

**Comment by mattleibow** [comment]
@TabishRafiq This is just for the native C++. We are moving from MSVC to Clang. For C#, nothing has changed and you will still use Roslyn/MSBuild. Also, this is just for our code, not any apps or libraries using SkiaSharp.

**Comment by TabishRafiq** [comment]
So the problem of slow drawing with rotated canvas has been solved on C#?

**Comment by mattleibow** [comment]
Yes. The actual drawing takes place in the C++ code, the C# was just a glue layer.

**Comment by TabishRafiq** [comment]
Cool, thank you! keep it up man your work is tremendous

**Pull request merged**
