### PR TITLE
Multitarget Views.Desktop.Common

### PR DESCRIPTION
**Pull request by bender2k14**
**Description of Change**

Changes `SkiaSharp.Views.Desktop.Common` to multitarget
- .NET Standard 2.0,
- .NET Framework 4.5, and
- .NET Core 3.0.

Also removes `SkiaSharp.Views.Desktop.Common.NetStandard`.

I don't know if any part of the automated builds/devops needs to change as well.  Someone should check that.

**Bugs Fixed**

Related to issue #1029.  This PR gets us closer to dual targeting .NET Framework and .NET Core for `SkiaSharp.Views.WPF`.

**API Changes**

None

**Behavioral Changes**

None (intended)

**PR Checklist**

- [ ] Has tests (if omitted, state reason in description)
- [ ] Rebased on top of master at time of PR
 - NA
- [x] Changes adhere to coding standard
- [ ] Updated documentation

### CODE REVIEW

**Comment by bender2k14** [comment]
> I don't know if any part of the automated builds/devops needs to change as well. Someone should check that.

Indeed, and I don't think I can help since I don't know why the build failed.

**Comment by bender2k14** [comment]
Oh, my bad.  That change was easy.  I could have figured that out by searching within the files for that project name.

**Comment by mattleibow** [comment]
Still failing for some reason. I'm AFK right now, I'll have a look as soon as I get back. Thanks for the PR. Not sure how I missed this one.

You might also want to have a look at the nuspec file and add the new platform.

**Comment by bender2k14** [comment]
I tried to force push but that wasn't working for some reason, so I deleted my branch and then pushed.  Deleting the branch closed this PR, and I don't have permission to reopen it, so I made a new one instead: #1067.

**Comment by mattleibow** [comment]
No prob.

**Pull request closed without merging**
