### PR TITLE
Bind SkPictureShader

### PR DESCRIPTION
**Pull request by alexandrvslv**
**Description of changes**

Allow create shaders from SKPicture

- Related to issue #969 

**API Changes**

Added: 
 
- `sk_shader_t SkiaApi.sk_shader_new_picture(sk_picture_t src, SKShaderTileMode tmx, SKShaderTileMode tmy, ref SKMatrix matrix, ref SKRect tile)`
- `SKShader SKShader.CreatePicture (SKPicture src, SKShaderTileMode tmx, SKShaderTileMode tmy, SKMatrix localMatrix, SKRect tile)`
- 'SKShaderTest.CanDrawWithCreatePictureShader()'

**Behavioral Changes**

As mentioned in [issue](https://github.com/mono/SkiaSharp/issues/969#issuecomment-535925348): existing native libraries already support this changes!

**PR Checklist**

- [x] Has tests
- [x] Rebased on top of master at time of PR
- [ ] Changes adhere to coding standard
- [ ] Updated documentation

### CODE REVIEW

**Comment by mattleibow** [comment]
Thanks for this PR @alexandrvslv! This looks like you first PR here, so welcome to prestigious position of code contributor!

I am having a look at the changes now and all looks really good. Just waiting on CI. 

I also just noticed that our CLA bot is still pending. Just wanted to check if you got a message to sign it? If not, then I think my suspicions that the bot is having issues is confirmed.

**Comment by alexandrvslv** [comment]
Thanks for feedback @mattleibow! 

I just recieved email notification about comments\notifications on this PR.

**Comment by FoggyFinder** [comment]
any updates?

**Comment by alexandrvslv** [comment]
Sorry, I miss CLA signing

**Comment by alexandrvslv** [comment]
I figured out the latest changes (codegen SkiApi). Maybe I'll close this PR and make a new one?

**Comment by FoggyFinder** [comment]
Why not just resolve conflicts?

**Comment by alexandrvslv** [comment]
> 
> 
> Why not just resolve conflicts?

Resolving don't handle the building error's, as of pinvoke changes require replace ref to &

**Comment by mattleibow** [comment]
I JUST did this, so sorry. Hopefully it is not too painful - you are going to be a guinea pig on this. Sorry.

You _should_ just be able to run this command in the SkiaSharp root:

```
dotnet run --project=utils/SkiaSharpGenerator/SkiaSharpGenerator.csproj -- generate --config binding/libSkiaSharp.json --skia externals/skia --output binding/Binding/SkiaApi.generated.cs
```

That just builds and runs the generator.

To fix the conflicts, just replace with entire contents with https://raw.githubusercontent.com/mono/SkiaSharp/master/binding/Binding/SkiaApi.cs

After all this, you should end up with your new API in the generated file.

**Comment by mattleibow** [comment]
Well, actually scrap that. Just nuke your changes to `SkiaApi.cs` by replacing the contents with https://raw.githubusercontent.com/mono/SkiaSharp/master/binding/Binding/SkiaApi.cs

The generator should automatically pick up new APIs as we go along.

**Comment by mattleibow** [comment]
With regards to changes, you can just edit in GitHub and we _should_ be good. Hopefully it is not too painful.

**Comment by alexandrvslv** [comment]
It's all by my misunderstanding of PR workflow.  Thanks for helping me to figure out, and for great feedback around just few lines of code)

**Comment by mattleibow** [comment]
No prob! No matter how small, it all matters in the end ;)

**Pull request merged**
