### PR TITLE
Implement `SKGLView` for .NET MAUI

### LINKED ISSUE #2050: SKGLView on .NET MAUI is missing a handler
I can’t use SKGLView because its handler is missing. SKCanvasView works fine.

```csharp
new SKGLView();
```

**Expected Behavior**

A working OpenGL view.

**Actual Behavior**

Runtime error saying no handler found.

**Basic Information**

- Version with issue:  latest
- Last known good version:  none 
- IDE:  VSMPreview
- Platform Target Frameworks:
  - macCatalyst:
- Target Devices:
  - Mac

### PR DESCRIPTION
**Pull request by mattleibow**
**Description of Change**

- Implemented SKGLView for Android, iOS and Windows
- Mac Catalyst will not get support - a new Metal-based view needs to be created
   - Maybe I can use a metal view instead of GL, or bind the GL view myself...
- Tizen first needs the support in the native view

**Bugs Fixed**

- Fixes #2050

**API Changes**

None.

**Behavioral Changes**

None.

**Required skia PR**

None.

**PR Checklist**

- [ ] Has tests (if omitted, state reason in description)
- [ ] Rebased on top of main at time of PR
- [ ] Merged related skia PRs
- [ ] Changes adhere to coding standard
- [ ] Updated documentation

### CODE REVIEW

**Comment by marcojak** [comment]
Hi Matthew, are there any plans to have a common hw accelerated view for a MAUI app for Android, iOS, Windows and Mac?

If not possible, how could I use an hw accelerated view on Windows? (and maybe a new one for Mac)?

**Comment by TopperDEL** [comment]
@marcojak This PR might be related for you: https://github.com/mono/SkiaSharp/issues/1893

**Comment by r2d2Proton** [comment]
Definitely would like this to work on all the platforms being targeted. Windows, Mac, etc.

**Comment by bogdan799** [comment]
@mattleibow I've sort of tested implementation of SKGLView on ios and android. I needed metal on iOS, so I've just replaced native view for SKGLViewHandler.iOS and seem to be fine, could be considered while implementing universal HW accelerated view. All seems to be much smoother than CPU rendering for my usecase, thank you for the solution.

However I've noticed following issue on android: 

Here when setting `Rendermode` to `RenderMode.WhenDirty`, repaint doesn't happen althouth I'm invalidating view many times:

SKGLViewHandler.Android.cs
```c#
public static void MapHasRenderLoop(SKGLViewHandler handler, ISKGLView view)
{
	handler.PlatformView.RenderMode = view.HasRenderLoop
		? Rendermode.Continuously
		: Rendermode.WhenDirty;
}
```

I checked following handler function, and seems you're using wrong method here:

```c#
// Mapper actions / properties

public static void OnInvalidateSurface(SKGLViewHandler handler, ISKGLView view, object? args)
{
	handler.PlatformView?.Invalidate();
}
```

According to MSDN:

Continuously | 1 | The renderer is called continuously to re-render the scene.
-- | -- | --
WhenDirty | 0 | The renderer only renders when the surface is created, or when RequestRender() is called.

Here's the change I've applied according to MSDN and it seem to work fine:

```c#
public static void OnInvalidateSurface(SKGLViewHandler handler, ISKGLView view, object? args)
{
	handler.PlatformView?.RequestRender();
}
```

**Comment by mattleibow** [comment]
Thanks @bogdan799! Your findings helped.

**Comment by levinli303** [comment]
Mac Catalyst has [CAOpenGLLayer](https://developer.apple.com/documentation/quartzcore/caopengllayer). You can have a UIView backed by CAOpenGLLayer and render OpenGL in the layer so that you don't have to mess with Metal.

**Comment by mattleibow** [comment]
I am not sure if it is exposed in the .NET bindings. They left out all the deprecated APIs for Mac Catalyst :(

**Comment by ToolmakerSteve** [comment]
@mattleibow I am getting the exception "Handler not found for view SkiaSharp.Views.Maui.Controls.SKGLView." in a fresh .Net Maui App project, targetting "Windows Machine", with an SKGLView added. 

Tested with Microsoft.Maui.Controls 8.0.40 + 
 SkiaSharp.Views & SkiaSharp.Views.Maui Controls
* latest stable 2.88.8, then tried
* latest preview 3.0.0-preview.3.1

Adding these two lines in appropriate places in MainPage.xaml:
`xmlns:sk="clr-namespace:SkiaSharp.Views.Maui.Controls;assembly=SkiaSharp.Views.Maui.Controls"`
`<sk:SKGLView WidthRequest="500" HeightRequest="300" BackgroundColor="Green" />`

Is this expected to work in Maui 8, or do I need a preview version of .Net Maui 9 Preview?

Should I create a new issue and/or upload a sample project?

**Comment by mattleibow** [comment]
Please open a new issue with a repro sample. GL should be working.

**Comment by ToolmakerSteve** [comment]
https://github.com/mono/SkiaSharp/issues/2860

**Comment by ToolmakerSteve** [comment]
@mattleibow - is there a plan to backport #2598 (Maui SKGLView fix) on Windows to 2.88.x?

Updating my client from .Net Framework 4.5 to .Net 8.

We've successfully updated on iOS and Android.  
(WITHOUT Maui; these are "platform native" .Net 8 apps, with GUI rendered via SkiaSharp. Plus some OpenGL.)

On Windows .Net 8, SkiaSharp 2.88.8 or .9, we've got everything EXCEPT OpenGL working. Using Maui SKCanvasView.

I made a new Maui app. Added SkiaSharp 2.88.9. Remembered to do "UseSkiaSharp()". Still get "Handler not found for view SkiaSharp.Views.Maui.Controls.SKGLView.".

Updating to SkiaSharp 3.118.0.0 preview, it works.  BUT this app is used in a production situation where failures must be very rare. So I can't use anything that isn't considered a stable release.

**Pull request merged**
