### PR TITLE
Update skia to m61

### PR DESCRIPTION
**Pull request by mattleibow**
Color Tables and Index8:
 - https://bugs.chromium.org/p/skia/issues/detail?id=6828 
 - https://skia-review.googlesource.com/c/skia/+/21664

SkBitmapScaler:
 - https://skia-review.googlesource.com/24644

### CODE REVIEW

**Comment by mikekinsman** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** File:../externals/skia not existed.
 - **[Error]** Some error ocurred while parsing changelist file: W:\mkrv-log-d228ce62\change-list-with-redirection.mapped.tsv.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C27%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201806271035234145-568%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=gXdY07jsq5H3PqqcNx2SeGGFuDLyBDSZKR4Insr0FtY%3D&st=2018-06-27T10%3A31%3A56Z&se=2018-07-28T10%3A36%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** File:../externals/skia not existed.
 - **[Error]** Some error ocurred while parsing changelist file: W:\wni1-log-12f19e9e\change-list-with-redirection.mapped.tsv.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C27%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201806271043172458-568%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=vA1jZK%2BQmxSBv%2B7iiIXLjsVAFY4KJUkaJg2j%2Bj%2ByO%2BM%3D&st=2018-06-27T10%3A39%3A47Z&se=2018-07-28T10%3A44%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** File:../externals/skia not existed.
 - **[Error]** Some error ocurred while parsing changelist file: W:\b3q1-log-7bd240f4\change-list-with-redirection.mapped.tsv.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C27%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201806271049458599-568%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=xqXcDzlnbTnM15AjMCHRWNU5%2BDHtz39DyW21ay4LPKI%3D&st=2018-06-27T10%3A46%3A19Z&se=2018-07-28T10%3A51%3A19Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** File:../externals/skia not existed.
 - **[Error]** Some error ocurred while parsing changelist file: W:\o4fy-log-b5ade514\change-list-with-redirection.mapped.tsv.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C27%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201806271051018758-568%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=HyykqTIt7Ae75YvdoRiLQXp5yfNHw4w5WE410VZfJyc%3D&st=2018-06-27T10%3A47%3A58Z&se=2018-07-28T10%3A52%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mattleibow** [comment]
build

**Comment by mikekinsman** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** File:../externals/skia not existed.
 - **[Error]** Some error ocurred while parsing changelist file: W:\dvfl-log-09812759\change-list-with-redirection.mapped.tsv.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C27%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201806271443091917-568%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=dIv7%2Fb6fKIK2ltLe%2BZEp%2BZmpNbS9Mbkh6CB%2Brf813ME%3D&st=2018-06-27T14%3A39%3A44Z&se=2018-07-28T14%3A44%3A44Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mattleibow** [comment]
Moving on to bigger and better things... namely m67. See #570

**Pull request closed without merging**
