### PR TITLE
Wrap SkPath Iter class. (#68)

### PR DESCRIPTION
**Pull request by tdenniston**
This allows for iterating over SKPaths. See also https://github.com/mono/skia/pull/10

### CODE REVIEW

**Comment by mattleibow** [comment]
@tdenniston, thanks for the PR! I'll have a look at it soon. Have you signed the CLA yet?

**Comment by tdenniston** [comment]
@mattleibow I haven't signed it yet, I'm still trying to figure that one out. I'm not sure I'm comfortable with a bot having admin access to my Github organizations, as those are tied to my professional life (these contributions are personal). I contacted Github support and there doesn't seem to be a way to disallow the bot access to my organizations. I may end up creating a new Github account for my professional work so that this can remain separate. If you want this PR but can't merge it until I sign the CLA, let me know and I'll expedite that process.

**Comment by bholmes** [comment]
@tdenniston we have fixed the cla bot to not request those roles.  You should be able to sign now with no worries.

**Comment by tdenniston** [comment]
@bholmes Great, thank you for that!

**Comment by migueldeicaza** [comment]
Any updates on getting the CLA signed?

**Comment by tdenniston** [comment]
@migueldeicaza I'm just waiting to hear from our technology licensing office, I'm not sure what's taking so long. I will ask them for an update. But in the meantime, I won't be offended if you want to reimplement this functionality and close this PR.

**Comment by migueldeicaza** [comment]
No problem!

I ended up adding both SKPath::Iter and SKPath::RawIter support, as they offer slightly different feature sets.   Would love if you could check them out.

**Pull request closed without merging**
