### PR TITLE
Add setting/getting fill type to SKPath.

### PR DESCRIPTION
**Pull request by petergolde**
Allows setting and getting the fill type in an SKPath. This is necessary, for example, to use the EvenOdd fill type. 

Note that changes to the skia C API were necessary also. You can see these changes in the petergolde/skia repo under the path-fill-type branch.

Edit:  Skia changes now in [PR 1][1] of mono/Skia

[1]: https://github.com/mono/skia/pull/1

### CODE REVIEW

**Comment by petergolde** [comment]
I have signed the CLA.

**Comment by bholmes** [comment]
I have verified that the CLA has been signed.

**Comment by bholmes** [comment]
We will have to pull [this commit](https://github.com/petergolde/skia/commit/45bdc31f6d735d23779b131c3e373047f2bbc8ac) into mono/skia and adjust the submodule changes of this patch.

**Comment by petergolde** [comment]
Is there a better way to handle pull requests that span a submodule? Should I create a simultaneous pull request in mono/skia? I'm new to github and pull requests so I don't know the best practices here. Please advise (I'm likely to have more PRs in the same vein...)

**Comment by bholmes** [comment]
@petergolde I think a PR in mono/skia would work well.  Be sure to link the skia PR in the comments here.

**Comment by petergolde** [comment]
See pull request #1 in mono/skia for the C part of this PR.

**Comment by bholmes** [comment]
Nice.  When we release this to NuGet we can also change the Xamagon sample to this...

	--- /Users/billholmes/Documents/Git-Xamarin/SkiaSharp/samples/SharedDemo/SkiaSharp.Demos.cs		(base)
	+++ /Users/billholmes/Documents/Git-Xamarin/SkiaSharp/samples/SharedDemo/SkiaSharp.Demos.cs		(working copy)
	@@ -47,6 +47,8 @@
	 
	 
	 				using (var path = new SKPath ()) {
	+					paint.Color = XamDkBlue;
	+
	 					path.MoveTo (71.4311121f, 56f);
	 					path.CubicTo (68.6763107f, 56.0058575f, 65.9796704f, 57.5737917f, 64.5928855f, 59.965729f);
	 					path.LineTo (43.0238921f, 97.5342563f);
	@@ -62,13 +64,6 @@
	 					path.LineTo (71.4311121f, 56f);
	 					path.Close ();
	 
	-					paint.Color = XamDkBlue;
	-					canvas.DrawPath (path, paint);
	-
	-				}
	-
	-				using (var path = new SKPath ()) {
	-
	 					path.MoveTo (71.8225901f, 77.9780432f);
	 					path.CubicTo (71.8818491f, 77.9721857f, 71.9440029f, 77.9721857f, 72.0034464f, 77.9780432f);
	 					path.LineTo (79.444074f, 77.9780432f);
	@@ -98,7 +93,8 @@
	 					path.LineTo (72.0034464f, 125.021957f);
	 					path.CubicTo (71.3274867f, 125.027814f, 70.8220664f, 124.157088f, 71.1600463f, 123.568869f);
	 					path.LineTo (83.4807624f, 101.500005f);
	 					path.LineTo (71.1600463f, 79.400867f);
	 					path.CubicTo (70.8647037f, 78.86725f, 71.2250368f, 78.0919422f, 71.8225901f, 77.9780432f);
	 					path.LineTo (71.8225901f, 77.9780432f);
	 					path.Close ();
	 
	-					paint.Color = SKColors.White;
	+					path.FillType = SKPathFillType.InverseWinding;
	+
	 					canvas.DrawPath (path, paint);
	 				}
	 			}

**Pull request merged**
