### PR TITLE
Dev/public builds

### PR DESCRIPTION
**Pull request by kdubau**

### CODE REVIEW

**Comment by mikekinsman** [comment]
OPS Build status updates of commit _[4243b2a](https://github.com/mono/SkiaSharp/pull/789/commits/4243b2ae33ab5e8427b620eb27294baf2175ba1d)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 59 sec(s)_

**Comment by mikekinsman** [comment]
OPS Build status updates of commit _[4243b2a](https://github.com/mono/SkiaSharp/pull/789/commits/4243b2ae33ab5e8427b620eb27294baf2175ba1d)_: 

:clock10: **Incremental building**: average incremental building time is _19 sec(s)_

**Comment by mikekinsman** [comment]
OPS Build status updates of commit _[4243b2a](https://github.com/mono/SkiaSharp/pull/789/commits/4243b2ae33ab5e8427b620eb27294baf2175ba1d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[scripts/azure-pipelines.yml](https://github.com/mono/SkiaSharp/blob/dev/public-builds/scripts/azure-pipelines.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C12%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201902122132458587-789%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=aGFBinhe6HAuHXeup5xmxpKUWuL%2BNpylKeyyIolPQRc%3D&st=2019-02-12T21%3A30%3A01Z&se=2019-03-15T21%3A35%3A01Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
OPS Build status updates of commit _[982c4da](https://github.com/mono/SkiaSharp/pull/789/commits/982c4daa116137c8f4c8285b7d2fb6aa2afefbf3)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 59 sec(s)_

**Comment by mikekinsman** [comment]
OPS Build status updates of commit _[982c4da](https://github.com/mono/SkiaSharp/pull/789/commits/982c4daa116137c8f4c8285b7d2fb6aa2afefbf3)_: 

:clock10: **Incremental building**: average incremental building time is _19 sec(s)_

**Comment by mikekinsman** [comment]
OPS Build status updates of commit _[982c4da](https://github.com/mono/SkiaSharp/pull/789/commits/982c4daa116137c8f4c8285b7d2fb6aa2afefbf3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[scripts/azure-pipelines.yml](https://github.com/mono/SkiaSharp/blob/dev/public-builds/scripts/azure-pipelines.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C12%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201902122144301031-789%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=0wyJv91Hi%2Bbn5sXDjuAddwGJUBA%2BdfcFdsDe%2FKoXYNM%3D&st=2019-02-12T21%3A41%3A44Z&se=2019-03-15T21%3A46%3A44Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
OPS Build status updates of commit _[bc37f12](https://github.com/mono/SkiaSharp/pull/789/commits/bc37f121fb45cf9e77fec1410d05ebb82408b0ec)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 59 sec(s)_

**Comment by mikekinsman** [comment]
OPS Build status updates of commit _[bc37f12](https://github.com/mono/SkiaSharp/pull/789/commits/bc37f121fb45cf9e77fec1410d05ebb82408b0ec)_: 

:clock10: **Incremental building**: average incremental building time is _19 sec(s)_

**Comment by mikekinsman** [comment]
OPS Build status updates of commit _[bc37f12](https://github.com/mono/SkiaSharp/pull/789/commits/bc37f121fb45cf9e77fec1410d05ebb82408b0ec)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[scripts/azure-pipelines.yml](https://github.com/mono/SkiaSharp/blob/dev/public-builds/scripts/azure-pipelines.yml) | :white_check_mark:Succeeded | |
[scripts/azure-templates-bootstrapper.yml](https://github.com/mono/SkiaSharp/blob/dev/public-builds/scripts/azure-templates-bootstrapper.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C12%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201902122154303048-789%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=KhGmwNgY1RaKyBWf10Euf8ND9dGT5vdp61FPP%2FnZQ90%3D&st=2019-02-12T21%3A51%3A54Z&se=2019-03-15T21%3A56%3A54Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
OPS Build status updates of commit _[e58b0c5](https://github.com/mono/SkiaSharp/pull/789/commits/e58b0c5b6bd04bf6409155edacd4014b536bfacd)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 59 sec(s)_

**Comment by mikekinsman** [comment]
OPS Build status updates of commit _[e58b0c5](https://github.com/mono/SkiaSharp/pull/789/commits/e58b0c5b6bd04bf6409155edacd4014b536bfacd)_: 

:clock10: **Incremental building**: average incremental building time is _19 sec(s)_

**Comment by mikekinsman** [comment]
OPS Build status updates of commit _[e58b0c5](https://github.com/mono/SkiaSharp/pull/789/commits/e58b0c5b6bd04bf6409155edacd4014b536bfacd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[scripts/azure-pipelines.yml](https://github.com/mono/SkiaSharp/blob/dev/public-builds/scripts/azure-pipelines.yml) | :white_check_mark:Succeeded | |
[scripts/azure-templates-bootstrapper.yml](https://github.com/mono/SkiaSharp/blob/dev/public-builds/scripts/azure-templates-bootstrapper.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C13%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201902131341201254-789%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Mfe1KtgxCYxGB5l36gpWHud6Bzdz9Ahd3yLcJGcVSg4%3D&st=2019-02-13T13%3A38%3A37Z&se=2019-03-16T13%3A43%3A37Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mattleibow** [comment]
Merged in https://github.com/mono/SkiaSharp/pull/790

**Pull request closed without merging**
