### PR TITLE
[WIP] Add GTK views for Xamarin.Forms

### LINKED ISSUE #379: Make SkiaSharp.Views.Forms support Xamarin Forms Gtk#
Xamarin Forms Gtk# Preview nuget package is on https://www.myget.org/F/xamarinforms-dev/api/v3/index.json

Thanks

> VS bug [#727964](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/727964)

### LINKED ISSUE #555: Convert a : Gdk.Pixbuf <-> SKImage/SKSurfafe/SKBitmap/SKPicture for Gtk
This exists in Gtk's  `SKWidget.OnExposeEvent()`:

https://github.com/mono/SkiaSharp/blob/master/source/SkiaSharp.Views/SkiaSharp.Views.Gtk/SKWidget.cs#L36

And it's a nice way to translate an SKSurface's drawing into a `Gdk.Pixbuf` object.  Though, there are some cases where It would be nice to paint an `Gdk.Pixbuf` onto an `SKSurface`.  Some conversion functions would be nice.

> VS bug [#736298](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/736298)

### PR DESCRIPTION
**Pull request by mattleibow**
**Description of Change**

Add some things to make GTK support better.

**Bugs Fixed**

- Fixes #379 (GTK# views for Forms)
- Fixes #555 (Helper methods)

**API Changes**

Added:

 - `GTKExtensions` for conversions (#555)
 - `SKCanvasViewRenderer` (need to investigate the scaling on this one)
 - NOT `SKGLViewRenderer` (there is code but it is excluded as it seems to be falling over)

**Behavioral Changes**

None.

**PR Checklist**

- [ ] Has tests (if omitted, state reason in description)
- [ ] Rebased on top of master at time of PR
- [ ] Changes adhere to coding standard
- [ ] Updated documentation

### CODE REVIEW

**Comment by yodadude2003** [comment]
Hello, 
I need this for a project I started working on a couple days ago. Convenient timing, right?
Just wondering when a nuget package will be published to the early access feed.  
Thanks in advance

**Comment by mattleibow** [comment]
I am hoping to push out a preview very soon. Just waiting on CI to go green. I'll post here again when it is out.

**Comment by mattleibow** [comment]
I just pushed out a preview (1.68.2-preview.17) to the preview feed so you can try it out now. I just want to do a few more checks and then it will go to nuget.org.

The preview feed is https://nugetized.blob.core.windows.net/skiasharp-eap/index.json

**Comment by yodadude2003** [comment]
Thanks, I appreciate it.  I'll try it out as soon as possible.

**Comment by mattleibow** [comment]
All was looking good, so I pushed out a preview to nuget.org. If there are any issues, just open a bug in the repo: https://www.nuget.org/packages/SkiaSharp/1.68.2-preview.17

**Comment by yodadude2003** [comment]
Thanks again.  Works great with my application and behaves as expected.  Good work!

**Pull request merged**
