### PR TITLE
Initial implementation for render-target concept (win32 sw-only)

### PR DESCRIPTION
**Pull request by kekekeks**
Initial code for #24. 

For now I'm struggling a bit with building opengl-renderer support (your scripts are skipping ANGLE build for some reason, so I need more time), so stub is used instead.

### CODE REVIEW

**Comment by kekekeks** [comment]
For example [this code](https://github.com/mono/SkiaSharp/blob/master/samples/Skia.WindowsDesktop.Demo/SkiaView.cs#L29) can be now simplified as:
```csharp
		protected override void OnPaint(PaintEventArgs e)
		{
			if (onDrawCallback == null)
				return;
		    using (var ctx = _renderTarget.CreateRenderContext())
                onDrawCallback(ctx.Canvas, Width, Height);
		}

```

**Comment by grokys** [comment]
Hi all, any feedback on this PR? We'd like to get our skia backend in [Perspex](https://github.com/Perspex/Perspex) using Skia# and this was intended as a first step.

Or if you already have plans for something to cover this, please let us know.

**Comment by danwalmsley** [comment]
Hi, I am also waiting on this PR!!!

**Comment by migueldeicaza** [comment]
This patch predates our use of the CLA bot, would you guys be so kind to resubmit the change, so that our CLA bot can request the signature?

**Comment by kekekeks** [comment]
Ehm. I've signed CLA as was requested by CLA bot in [this PR](https://github.com/mono/SkiaSharp/pull/29) which was at March the 1st. This PR was submitted at March the 3rd.

**Comment by mattleibow** [comment]
Thanks for this PR, but before I merge this in I want to have a look at getting the GPU bits working for all the platforms. 

Right now, I am looking at other issues in SkiaSharp as well as updating our Skia to the "latest", or rather m52. Once this is done, I will start on the GPU/render targets.

WRT the update, I am nearly done. I just have a few kinks to work out with Android ARMv6

**Pull request closed without merging**
