### PR TITLE
testing

### PR DESCRIPTION
**Pull request by mattleibow**

### CODE REVIEW

**Comment by mikekinsman** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[scripts/pipeline.groovy](https://github.com/mono/SkiaSharp/blob/dev/artifacts/scripts/pipeline.groovy) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C19%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201809191143323907-638%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Br3gI1giFjvd4K%2BFQF6ZWt002IOGYRq8d3mtWt6GK9g%3D&st=2018-09-19T11%3A40%3A46Z&se=2018-10-20T11%3A45%3A46Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[scripts/pipeline.groovy](https://github.com/mono/SkiaSharp/blob/dev/artifacts/scripts/pipeline.groovy) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C19%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201809191155164614-638%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=tJuq8ILh3WrIpn7jMNDpNa%2FqdvomM305DVb99DYtxHc%3D&st=2018-09-19T11%3A52%3A32Z&se=2018-10-20T11%3A57%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[scripts/pipeline.groovy](https://github.com/mono/SkiaSharp/blob/dev/artifacts/scripts/pipeline.groovy) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C19%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201809191156550468-638%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=7k0fb9WIkXJd6Id2kjg5%2FrGp%2Bnl9Dhs7UevJAGp7Ayo%3D&st=2018-09-19T11%3A54%3A51Z&se=2018-10-20T11%3A59%3A51Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[scripts/pipeline.groovy](https://github.com/mono/SkiaSharp/blob/dev/artifacts/scripts/pipeline.groovy) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C19%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201809191158147849-638%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=3uQBdHwrFoxxdqKW9xhhPZ5gxRkLgZDDLHbos6fI%2Bdw%3D&st=2018-09-19T11%3A57%3A15Z&se=2018-10-20T12%3A02%3A15Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[scripts/pipeline.groovy](https://github.com/mono/SkiaSharp/blob/dev/artifacts/scripts/pipeline.groovy) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C19%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201809191301267627-638%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=wVXHf6hhhtVcMXt8CZQDaX9cDz517pO%2BFHfrkILuW%2Fk%3D&st=2018-09-19T12%3A58%3A45Z&se=2018-10-20T13%3A03%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[scripts/pipeline.groovy](https://github.com/mono/SkiaSharp/blob/dev/artifacts/scripts/pipeline.groovy) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C19%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201809191304476992-638%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=7MSlxcUvoi1rNteHCyOQpIDsbfOlo6eZ9coIG2Bsx5I%3D&st=2018-09-19T13%3A02%3A12Z&se=2018-10-20T13%3A07%3A12Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[scripts/pipeline.groovy](https://github.com/mono/SkiaSharp/blob/dev/artifacts/scripts/pipeline.groovy) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C19%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201809191306218363-638%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=QAuuB7XkHB7JYLmeRCsOJG6Uw5HlCtMPvp1cCvsmyIU%3D&st=2018-09-19T13%3A04%3A35Z&se=2018-10-20T13%3A09%3A35Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[scripts/pipeline.groovy](https://github.com/mono/SkiaSharp/blob/dev/artifacts/scripts/pipeline.groovy) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C19%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201809191326571604-638%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=YhOFsAVYkDTIajvCNKX4UvKKLCNtK%2FhSeBMeGZ97TzQ%3D&st=2018-09-19T13%3A24%3A11Z&se=2018-10-20T13%3A29%3A11Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[scripts/pipeline.groovy](https://github.com/mono/SkiaSharp/blob/dev/artifacts/scripts/pipeline.groovy) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C19%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201809191412222809-638%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=7wQoBJ67tqBrScWF%2ByjYX36aUQYCfhpg0RHFdvNMFtU%3D&st=2018-09-19T14%3A09%3A39Z&se=2018-10-20T14%3A14%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[scripts/pipeline.groovy](https://github.com/mono/SkiaSharp/blob/dev/artifacts/scripts/pipeline.groovy) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C19%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201809191539325327-638%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=sIAUszxyb2MkUWbKNI4mI%2BTR1F4oUMI9zPvlWegjdnY%3D&st=2018-09-19T15%3A36%3A47Z&se=2018-10-20T15%3A41%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mattleibow** [comment]
build

**Comment by mattleibow** [comment]
build

**Comment by mikekinsman** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[cake/BuildExternals.cake](https://github.com/mono/SkiaSharp/blob/dev/artifacts/cake/BuildExternals.cake) | :white_check_mark:Succeeded | |
[scripts/pipeline.groovy](https://github.com/mono/SkiaSharp/blob/dev/artifacts/scripts/pipeline.groovy) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C20%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201809201235099096-638%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ISj8UxwBz9wbFrv6eTzE%2FQbahz4AOJF3%2F9ihGGw2924%3D&st=2018-09-20T12%3A32%3A26Z&se=2018-10-21T12%3A37%3A26Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[build.cake](https://github.com/mono/SkiaSharp/blob/dev/artifacts/build.cake) | :white_check_mark:Succeeded | |
[cake/BuildExternals.cake](https://github.com/mono/SkiaSharp/blob/dev/artifacts/cake/BuildExternals.cake) | :white_check_mark:Succeeded | |
[scripts/pipeline.groovy](https://github.com/mono/SkiaSharp/blob/dev/artifacts/scripts/pipeline.groovy) | :white_check_mark:Succeeded | |
[source/SkiaSharp.Build.targets](https://github.com/mono/SkiaSharp/blob/dev/artifacts/source/SkiaSharp.Build.targets) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C20%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201809201328263203-638%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=raCqpBM5YxFiXo%2Bs8OcCfrkimchY7i%2BHDRi9VLynnn4%3D&st=2018-09-20T13%3A25%3A42Z&se=2018-10-21T13%3A30%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[build.cake](https://github.com/mono/SkiaSharp/blob/dev/artifacts/build.cake) | :white_check_mark:Succeeded | |
[cake/BuildExternals.cake](https://github.com/mono/SkiaSharp/blob/dev/artifacts/cake/BuildExternals.cake) | :white_check_mark:Succeeded | |
[scripts/pipeline.groovy](https://github.com/mono/SkiaSharp/blob/dev/artifacts/scripts/pipeline.groovy) | :white_check_mark:Succeeded | |
[source/SkiaSharp.Build.targets](https://github.com/mono/SkiaSharp/blob/dev/artifacts/source/SkiaSharp.Build.targets) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C20%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201809201628491486-638%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2FvG8vbT1crSfKj17hzix3F66sfffBJMnhE1PR5FCuC4%3D&st=2018-09-20T16%3A26%3A03Z&se=2018-10-21T16%3A31%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[build.cake](https://github.com/mono/SkiaSharp/blob/dev/artifacts/build.cake) | :white_check_mark:Succeeded | |
[cake/BuildExternals.cake](https://github.com/mono/SkiaSharp/blob/dev/artifacts/cake/BuildExternals.cake) | :white_check_mark:Succeeded | |
[scripts/pipeline.groovy](https://github.com/mono/SkiaSharp/blob/dev/artifacts/scripts/pipeline.groovy) | :white_check_mark:Succeeded | |
[source/SkiaSharp.Build.targets](https://github.com/mono/SkiaSharp/blob/dev/artifacts/source/SkiaSharp.Build.targets) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C20%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201809201755317465-638%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=uCBOD31ObKJ%2FcM2CU9xnNtoHU4Tte1tHs8j01F%2FpF10%3D&st=2018-09-20T17%3A52%3A51Z&se=2018-10-21T17%3A57%3A51Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mikekinsman** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[build.cake](https://github.com/mono/SkiaSharp/blob/dev/artifacts/build.cake) | :white_check_mark:Succeeded | |
[cake/BuildExternals.cake](https://github.com/mono/SkiaSharp/blob/dev/artifacts/cake/BuildExternals.cake) | :white_check_mark:Succeeded | |
[scripts/pipeline.groovy](https://github.com/mono/SkiaSharp/blob/dev/artifacts/scripts/pipeline.groovy) | :white_check_mark:Succeeded | |
[source/SkiaSharp.Build.targets](https://github.com/mono/SkiaSharp/blob/dev/artifacts/source/SkiaSharp.Build.targets) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C20%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201809201802163721-638%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=88wg3BAfHUpu5aL40ke3B4FItW%2BuoAfLDLlCt1T%2F%2FM0%3D&st=2018-09-20T17%3A59%3A40Z&se=2018-10-21T18%3A04%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
