### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mattleibow**

### CODE REVIEW

**Comment by mikekinsman** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[README.md](https://github.com/mono/SkiaSharp/blob/dev/build-pr/README.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C10%5C15%5C81ca5486-8c50-0a94-05c4-486e23e99ecf%5CPullRequest%5C201810151511510635-653%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=nI8geF8bZq246%2FOa58MNL64nLgCuYIxuFPtRKQaRIAY%3D&st=2018-10-15T15%3A09%3A07Z&se=2018-11-15T15%3A14%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by akoeplinger** [comment]
@monojenkins build

**Comment by akoeplinger** [comment]
@monojenkins build

**Comment by akoeplinger** [comment]
@monojenkins build

**Pull request closed without merging**
