### PR TITLE
Bumps to Uno 4.0

### PR DESCRIPTION
**Pull request by jeromelaban**
**Description of Change**

This change bumps Uno to 4.0 preview bits, which include binary breaking changes.

**Bugs Fixed**

None

- Related to issue #

**API Changes**

None

**Behavioral Changes**

Nonoe.

**PR Checklist**

- [ ] ~~Has tests (if omitted, state reason in description)~~
- [x] Rebased on top of main at time of PR
- [x] Changes adhere to coding standard
- [ ] Updated documentation

### CODE REVIEW

**Comment by jeromelaban** [comment]
@mattleibow I assume the build errors are caused by the inclusion of nuget.org in the nuget.config file, though I'm not able to build locally as nuget.org packages are missing. What's the correct route to fix this ? Thanks!

**Comment by robloo** [comment]
@jeromelaban @mattleibow This is an important issue as without it fixed Skia cannot be used with Uno Platform (UWP projects).

On my end attempting to construct an `SKXamlCanvas` with Skia preview version 2.88.0-preview.155 (SkiaSharp & SkiaSharp.Views.Uno) throws the exception:

{System.TypeLoadException: Could not resolve type with token 0100007b from typeref (expected class 'Windows.UI.Core.UIAsyncOperation' in assembly 'Uno, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null')
  at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine] (TStateMachine& stateMachine) [0x0002c] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:84 
  at SkiaSharp.Views.UWP.SKXamlCanvas.Invalidate () [0x00007] in <b29578e77edf45458b8e1c6cb6b3ad98>:0 
  at SkiaSharp.Views.UWP.SKXamlCanvas.OnDpiChanged (Windows.Graphics.Display.DisplayInformation sender, System.Object args) [0x00013] in D:\a\1\s\source\SkiaSharp.Views.Uno\SkiaSharp.Views.Uno\SKXamlCanvas.cs:83 
  at SkiaSharp.Views.UWP.SKXamlCanvas.Initialize () [0x0000e] in D:\a\1\s\source\SkiaSharp.Views.Uno\SkiaSharp.Views.Uno\SKXamlCanvas.cs:36 
  at SkiaSharp.Views.UWP.SKXamlCanvas..ctor () [0x00027] in D:\a\1\s\source\SkiaSharp.Views.Uno\SkiaSharp.Views.Uno.Android\SKXamlCanvas.Android.cs:14 
  at FinancialManager.UWP.Controls.LineChart..ctor () [0x00177] in ...\Source\Controls\Charts\LineChart\LineChart.cs:108 }

**Comment by mikebmcl** [comment]
Is there any timeframe for this patch being applied and pushed to nuget? Possibly applied against 2.80.3 and published as a minor update of that if 2.88 isn't likely to be ready for release soon?

I've been tinkering with a replacement for my use of SkiaSharp and I'm almost at the point where I need to decide if I'm going to commit to that. Knowing the expected timeframe for this would help me greatly. Thanks!

**Review by mattleibow — APPROVED** [review]

**Comment by robloo** [comment]
This corresponds with the SkiaSharp 2.88.0-preview.179 nuget (including SkiaSharp.Views and SkiaSharp.Views.Uno)

Any Uno version < 4.0 must use SkiaSharp < 2.88.0-preview.179 and
Any Uno version >= 4.0 must use SkiaSharp >= 2.88.0-preview.179

**Pull request merged**
