### PR TITLE
Update HarfBuzz 2.5.2

### PR DESCRIPTION
**Pull request by Gillibald**
- Windows [x] 
- Linux [x] 
- Tizen [x] 
- Android [x] 
- Mac [x] 

On Linux the compiler seems to have issues. Can we use clang to build HarfBuzz?
@mattleibow

### CODE REVIEW

**Comment by mattleibow** [comment]
@Gillibald We can and probably should.
But, I see 2.5.2 has fixes for GCC 4.8 - so that might fix it.

**Comment by Gillibald** [comment]
This is already HarfBuzz 2.5.2

**Comment by mattleibow** [comment]
In that case, we can switch to clang. I don't think there is a real preference for compilers.

**Comment by Gillibald** [comment]
Looks like the current Android compiler doesn't like C++11

**Comment by Gillibald** [comment]
Linux and Android are blocked by compiler. For Mac Codex projects need and update I can't do.

**Comment by mattleibow** [comment]
I switched to using clang for both Linux and Android, and then upgraded the Android build to C++11.
I also added the files to the xcode projects. Let's see how this goes...

**Comment by mattleibow** [comment]
@Gillibald I think we are good to merge. Let me know if you spot anything that I missed.

**Comment by Gillibald** [comment]
Looks good now 👍

**Pull request merged**
