### PR TITLE
Option to disable automatic resizing of the canvas

### PR DESCRIPTION
**Pull request by Code-Chops**
At the moment it's not possible to disable automatic resizing of the canvas. Besides that there is a bug in the automatic resizing, I don't want the functionality at all for my project.

I added parameter 'AutoResize' to SKGLView and SKCanvasView (which is true by default). When it is disabled, the SizeWatcherInterop won't be used.

See issue:
https://github.com/mono/SkiaSharp/issues/1896

Added: 
 
```
/// <summary>
/// If true (default), the canvas will be automatically resized to fit the client width and height. 
/// </summary>
[Parameter]
public bool AutoResize { get; set; } = true;
```

### CODE REVIEW

**Comment by robloo** [comment]
It looks like if you set AutoResize from false to true nothing will happen until the next paint. It might be a good idea, in the AutoResize property setter, to handle changes and then refresh things.

**Comment by Daendel** [comment]
I changed the code so that the AutoResize script will always be imported. Observing is not started anymore when the script is loaded, but will start when the AutoResize-proprety is set to true. If the property is set to false, the element will not be observed anymore.

**Comment by mattleibow** [comment]
Are you talking about this bug: https://github.com/mono/SkiaSharp/pull/1889

**Comment by Daendel** [comment]
Yes :)

**Comment by mgood7123** [comment]
why would you want to disable automatic resizing?

**Comment by mattleibow** [comment]
I think if you want to disable auto-resizing maybe you just need to set a fixed with/height?

**Comment by mgood7123** [comment]
> I think if you want to disable auto-resizing maybe you just need to set a fixed with/height?

heavily agreed

**Comment by ViRuSTriNiTy** [comment]
Fixed with and height can be enforced via CSS, see solution posted here: https://github.com/mono/SkiaSharp/issues/2038#issuecomment-1129008602

**Pull request closed without merging**
